### ISSUE TITLE
有關 readme.md 內的問題

### ISSUE THREAD

**Issue by LianSheng197** [hgalytoby/MyselfAnimeDownloader#1]
```diff
! 先說結論：我沒有遇到找不到 data-href 的問題（採用你附的程式碼是可以正常運作的）
```

### 原始問題節錄
> 網頁上的 source 碼 與 requests.get 後的結果。
> 
> ![image](https://i.imgur.com/9kG6vdj.png)
> ```python
> import requests  
>   
> url = 'https://myself-bbs.com/forum.php?mod=viewthread&tid=43773&highlight=%E7%99%BD%E8%89%B2%E7%9B%B8%E7%B0%BF'  
> headers = {  
>     'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'}  
> res = requests.get(url=url, headers=headers)  
> print(res.text)
> ```
> 發現沒辦法取得到圖上紅框的 url。
> 接著我有將 header 加入更多的參數，以及丟cookies，依然沒有辦法取得URL。

***
### 我的環境
```bash
python3 --version

# Python 3.7.5
```
```bash
pip3 show requests

# Name: requests
# Version: 2.21.0
# Summary: Python HTTP for Humans.
# Home-page: http://python-requests.org
# Author: Kenneth Reitz
# Author-email: me@kennethreitz.org
# License: Apache 2.0
# Location: /usr/lib/python3/dist-packages
# Requires: 
# Required-by: 
```

### 執行程式碼
```py
import requests  
  
url = 'https://myself-bbs.com/forum.php?mod=viewthread&tid=43773&highlight=%E7%99%BD%E8%89%B2%E7%9B%B8%E7%B0%BF'  
headers = {  
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'
}  
res = requests.get(url=url, headers=headers)  
with open("dump.html", "w") as f:
    f.write(res.text)
```

### 結果
![Selection_035](https://user-images.githubusercontent.com/18535495/89751168-8c172a00-db01-11ea-8017-ad1b349fa67c.png)

另外我用過 curl 去請求相同網址，得出來的結果一樣含有 data-href 與完整網址，可以確定這部份是由網頁直接產生的，而不是經過 JavaScript 二階段產生。

不曉得你具體是遇到什麼問題呢？

**Comment by LianSheng197** [comment]
這裡附上簡短程式碼，抓取「第 n 話」與「網址」

```py
import requests
from bs4 import BeautifulSoup
  
url = 'https://myself-bbs.com/forum.php?mod=viewthread&tid=43773&highlight=%E7%99%BD%E8%89%B2%E7%9B%B8%E7%B0%BF'  
headers = {  
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36'
}  
res = requests.get(url=url, headers=headers)  

soup = BeautifulSoup(res.text, 'html.parser')

result = soup.select("ul.display_none")
result = list(map(lambda x: [x.find_previous_sibling("a").text, x.select_one("a")["data-href"].replace("\r", "").replace("\n", "")], result))

print(result)
```

參考結果
```text
[['第 01 話', 'https://v.myself-bbs.com/player/play/43773/001'], ['第 02 話', 'https://v.myself-bbs.com/player/play/43773/002'], ['第 03 話', 'https://v.myself-bbs.com/player/play/43773/003'], ['第 04 話', 'https://v.myself-bbs.com/player/play/43773/004'], ['第 05 話', 'https://v.myself-bbs.com/player/play/43773/005'], ['第 06 話', 'https://v.myself-bbs.com/player/play/43773/006'], ['第 07 話', 'https://v.myself-bbs.com/player/play/43773/007'], ['第 08 話', 'https://v.myself-bbs.com/player/play/43773/008'], ['第 09 話', 'https://v.myself-bbs.com/player/play/43773/009'], ['第 10 話', 'https://v.myself-bbs.com/player/play/43773/010'], ['第 11 話', 'https://v.myself-bbs.com/player/play/43773/011'], ['第 12 話', 'https://v.myself-bbs.com/player/play/43773/012'], ['第 13 話', 'https://v.myself-bbs.com/player/play/43773/013']]
```

**Comment by hgalytoby** [comment]
前半段code
![image](https://i.imgur.com/UCcl5fb.png)

後半段
![image](https://i.imgur.com/UCcl5fb.png)

太好了  如果這樣能穩穩取得 那我的可以把queue拔掉減少記憶體了

**Comment by hgalytoby** [comment]
> 這裡附上細分程式碼，抓取「第n話」與「網址」
> 
> ```python
> 進口 請求
> 從 BS4  進口 BeautifulSoup
>   
> url  =  'https:   
> //myself-bbs.com/forum.php  ? mod = viewthread& tid = 43773& highlight =% E7%99%BD%E8%89%B2%E7%9B%B8%E7%B0% BF' 標頭= {  
>      'User-Agent'：'Mozilla / 5.0（Windows NT 10.0; Win64; x64）AppleWebKit / 537.36（KHTML，like Gecko）Chrome / 84.0.4147.105 Safari / 537.36'
> }  
> res  =  請求。獲取（url = url，headers = headers）  
> 
> 湯 =  BeautifulSoup（RES。文本，'html.parser' ）
> 
> 結果 =  湯。選擇（“ul.display_none” ）
>  結果 =  列表（地圖（拉姆達 X：[ X。find_previous_sibling（“一”）。文本，X。select_one（“一”）[ “數據HREF” ]。替換（“ \ r “，”“）。replace（” \ n “，”“）]]，結果））
> 
> 打印（結果）
> ```
> 
> 參考結果
> 
> ```
> [['第 01 話', 'https://v.myself-bbs.com/player/play/43773/001'], ['第 02 話', 'https://v.myself-bbs.com/player/play/43773/002'], ['第 03 話', 'https://v.myself-bbs.com/player/play/43773/003'], ['第 04 話', 'https://v.myself-bbs.com/player/play/43773/004'], ['第 05 話', 'https://v.myself-bbs.com/player/play/43773/005'], ['第 06 話', 'https://v.myself-bbs.com/player/play/43773/006'], ['第 07 話', 'https://v.myself-bbs.com/player/play/43773/007'], ['第 08 話', 'https://v.myself-bbs.com/player/play/43773/008'], ['第 09 話', 'https://v.myself-bbs.com/player/play/43773/009'], ['第 10 話', 'https://v.myself-bbs.com/player/play/43773/010'], ['第 11 話', 'https://v.myself-bbs.com/player/play/43773/011'], ['第 12 話', 'https://v.myself-bbs.com/player/play/43773/012'], ['第 13 話', 'https://v.myself-bbs.com/player/play/43773/013']]
> ```
