### ISSUE TITLE
有幾點想幫忙改善一下的

### ISSUE THREAD

**Issue by Garytang01** [hgalytoby/MyselfAnimeDownloader#10]
你好, 這個非常方便, 先感謝, 
有幾點想幫忙改善一下的,  
1, 最小化可否不直接去到狀態列可以嗎
2, 由於我的WIN 工作列設定了上方,  開程式時可否不要在左上方開, 因為已經不能移動,,  被工作列遮蔽了,

謝謝

**Comment by hgalytoby** [comment]
> 你好，這個非常方便，先感謝，
> 有一些想幫忙改善一下的，
> 1，最小化可否不直接去到狀態列可以嗎
> 2，由於我的WIN工作列設置了上方，開程式時可否不要在左上方開，因為已經不能移動,,被工作列遮蔽了，
> 
> 謝謝

1. 可以最下話不要去狀態列。

2. 開程式不要左上方開是什麼意思?指的是程式打開後在左上角嗎??這個是作業系統規定的好像不是我能控制的。

**Comment by hgalytoby** [comment]
> > 你好，這個非常方便，先感謝，
> > 有一些想幫忙改善一下的，
> > 1，最小化可否不直接去到狀態列可以嗎
> > 2，由於我的WIN工作列設置了上方，開程式時可否不要在左上方開，因為已經不能移動,,被工作列遮蔽了，
> > 謝謝
> 
> 1. 可以最下話不要去狀態列。
> 2. 開程式不要左上方開是什麼意思?指的是程式打開後在左上角嗎??這個是作業系統規定的好像不是我能控制的，我增加一個按住程式背景就能移動的功能如何?

**Comment by hgalytoby** [comment]
> 你好, 這個非常方便, 先感謝,
> 有幾點想幫忙改善一下的,
> 1, 最小化可否不直接去到狀態列可以嗎
> 2, 由於我的WIN 工作列設定了上方, 開程式時可否不要在左上方開, 因為已經不能移動,, 被工作列遮蔽了,
> 
> 謝謝

已經更新了。

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.2

**Comment by Garytang01** [comment]
問題解決了,  感謝, 星已按,

**Comment by hgalytoby** [comment]
> 問題解決了, 感謝, 星已按,

謝謝您，還有新的想法請在留言給我。
