### ISSUE TITLE
WIN10 ver1809 企業版 莫名閃退

### ISSUE THREAD

**Issue by yanyan8566** [hgalytoby/MyselfAnimeDownloader#11]
作者您好：

如標題所示，在 windows 10 1809 企業版中，進行下載時會程式會無預警的關閉，關閉後欲再開啟程式及出現以下錯誤。
![螢幕擷取畫面 2021-05-22 170520](https://user-images.githubusercontent.com/62531742/119221113-58e9d880-bb20-11eb-8a94-d49ddc6ab995.png)

**Comment by hgalytoby** [comment]
> 作者您好：
> 
> 如標題所示，在 windows 10 1809 企業版中，進行下載時會程式會無預警的關閉，關閉後欲再開啟程式及出現以下錯誤。
> ![螢幕擷取畫面 2021-05-22 170520](https://user-images.githubusercontent.com/62531742/119221113-58e9d880-bb20-11eb-8a94-d49ddc6ab995.png)

你好~

之前也有人遇到這個問題，那時候的解法是重新下載一次程式就解決了。

你試試看。

**Comment by zirotee** [comment]
虽然我的不是企业版而是教育版20H2, 解压缩后打开myself bbs后也是无法打开

**Comment by hgalytoby** [comment]
> 虽然我的不是企业版而是教育版20H2, 解压缩后打开myself bbs后也是无法打开

你好~

請重新下載程式試試看。

如果以上都不行，請幫我下載 https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/V1.2.1test

請幫我照常執行，你會看到多出一個視窗。

![image](https://user-images.githubusercontent.com/50397689/119224981-ae7bb080-bb33-11eb-89e5-164ecd51c63d.png)

當 `Failed to execute script main` 發生時，截圖讓我看黑色視窗顯示的是什麼錯誤。

**Comment by zirotee** [comment]
> > 虽然我的不是企业版而是教育版20H2, 解压缩后打开myself bbs后也是无法打开
> 
> 你好~
> 
> 請重新下載程式試試看。
> 
> 如果以上都不行，請幫我下載 https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/V1.2.1test
> 
> 請幫我照常執行，你會看到多出一個視窗。
> 
> ![image](https://user-images.githubusercontent.com/50397689/119224981-ae7bb080-bb33-11eb-89e5-164ecd51c63d.png)
> 
> 當 `Failed to execute script main` 發生時，截圖讓我看黑色視窗顯示的是什麼錯誤。

没事了，我发现打开程序的时候需要以管理员运行才能打开，而且如果在浏览器上连不到Myself 動漫網的话也无法正常运行这个软件（我开vpn前忘了拍起来），打开后一段时间就会自己关掉，所以我用了vpn才能正常运行。请问打开程序时需要以管理员运行才能打开这是正常吗？

**Comment by hgalytoby** [comment]
> 没事了，我发现打开程序的时候需要以管理员运行才能打开，
> 而且如果在浏览器上连不到Myself 動漫網的话也无法正常运行这个软件，打开后一段时间就会自己关掉，所以我用了vpn才能正常运行。
> 请问打开程序时需要以管理员运行才能打开这是正常吗？

我沒有寫很多防呆機制，確實可能是讀取不到 Myself 動漫網會可能因為報錯而關閉程式。

我不知道其他作業系統如何，我是旗艦版點兩下執行就好了，並不需要用工作管理員執行。

**Comment by hgalytoby** [comment]
> > 没事了，我发现打开程序的时候需要以管理员运行才能打开，
> > 而且如果在浏览器上连不到Myself 動漫網的话也无法正常运行这个软件，打开后一段时间就会自己关掉，所以我用了vpn才能正常运行。
> > 请问打开程序时需要以管理员运行才能打开这是正常吗？
> 
> 我沒有寫很多防呆機制，確實可能是讀取不到 Myself 動漫網會可能因為報錯而關閉程式，我的首頁也有說如果Myself 動漫畫關閉的話就無法使用。
> 
> 我不知道其他作業系統如何，我是旗艦版點兩下執行就好了，並不需要用工作管理員執行。

**Comment by hgalytoby** [comment]
這個問題就先關閉了。

如果還有問題請再發問。

謝謝。
