### ISSUE TITLE
Use Python 3.8.2 to pip3 install requirements.txt error with PyQt5

### ISSUE THREAD

**Issue by yanyan8566** [hgalytoby/MyselfAnimeDownloader#12]
作者您好：

如以下圖片所示，當使用 pip3 install -r requirements.txt 時，在安裝 PyQt5 的時候就會出現以下錯誤，請問以下套件是不支援 python 3.8.2 嗎？另外我的 pip 版本是 19.2.3。

![2021-06-19 17-46-52 的螢幕擷圖](https://user-images.githubusercontent.com/62531742/122638449-baed2c00-d126-11eb-8004-cde0076291b5.png)

**Comment by hgalytoby** [comment]
> 作者您好：
> 
> 如以下圖片所示，當使用 pip3 install -r requirements.txt 時，在安裝 PyQt5 的時候就會出現以下錯誤，請問以下套件是不支援 python 3.8.2 嗎？另外我的 pip 版本是 19.2.3。
> 
> ![2021-06-19 17-46-52 的螢幕擷圖](https://user-images.githubusercontent.com/62531742/122638449-baed2c00-d126-11eb-8004-cde0076291b5.png)

升級 pip 試試看

`python -m pip install --upgrade pip ‵

**Comment by hgalytoby** [comment]
如果還有問題請再告知，謝謝。
