### ISSUE TITLE
MacOS v1.1.3版 開啟後顯示作者更新了然後退出 無法使用

### ISSUE THREAD

**Issue by leocyl** [hgalytoby/MyselfAnimeDownloader#13]
![螢幕截圖 2021-08-20 下午1 55 27](https://user-images.githubusercontent.com/30165122/130186606-069966e5-4f00-45a4-a98a-5051606fcb87.png)

**Comment by hgalytoby** [comment]
顯示作者更新看起來是我包成 .app 的時候，沒用到最新的程式包成 .app (是我的失誤)。

但是我這邊顯示作者更新了，按下 OK 或者按下左上角 Ｘ圖示，接著按下左上角 X 顯示是否離開程式，選擇 Yes 離開程式。

再度打開程式都沒有問題。

請問您說的無法使用是指哪個不能使用？

**Comment by leocyl** [comment]
https://user-images.githubusercontent.com/30165122/130195207-e4039f23-0acb-4caa-916d-e08d4a9d46ad.mp4

**Comment by leocyl** [comment]
原來是按下後間歇性會自動縮小到上方的小圖示，暫時可以使用了，謝謝你！！

**Comment by hgalytoby** [comment]
> 原來是按下OK後間歇性會自動縮小到上方的小圖示，暫時可以使用了，謝謝你！！

你的影片讓我很訝異!!

我剛剛也用 Mac 做了跟你一樣拖曳視窗的操作，我的也會被突然縮小下去，目前的解決辦法是，請你到設定那邊將縮小到狀態列那個功能關掉，這樣就不會無緣無故拖曳視窗就縮小了。

這算是我的 Bug ，近期研究好我會再推新的一版上來，謝謝您。

**Comment by hgalytoby** [comment]
> 原來是按下OK後間歇性會自動縮小到上方的小圖示，暫時可以使用了，謝謝你！！

我更新版本 1.1.4 了，新的版本只是不給 Mac 使用縮小到工具列的問題而已，其餘沒什麼改動，看您要不要下載。
