### ISSUE TITLE
大神求救

### ISSUE THREAD

**Issue by YomiaTW** [hgalytoby/MyselfAnimeDownloader#14]
本人非python使用者

使用您的程式1.1.4 on windows 10 專業版64位元 更新到最新

設定下載路徑後嘗試下載檔案，一次一個，顯示0%下載中無進度

求指教 感恩

**Comment by Dovah614** [comment]
不好意思
2024的現在
不知道是不是來晚了?
現在下載都卡在0%
只有一個檔案一度衝到14%就又卡住
有照上方的指示去看看防毒軟體
為此還把防毒給砍了
也重載檔案
從此就卡在0%了

**Comment by hgalytoby** [comment]
> 不好意思 2024的現在 不知道是不是來晚了? 現在下載都卡在0% 只有一個檔案一度衝到14%就又卡住 有照上方的指示去看看防毒軟體 為此還把防毒給砍了 也重載檔案 從此就卡在0%了

你下載哪個動漫? 我幫你測試看看?

可能是官方就不能看了。

**Comment by Dovah614** [comment]
不知道為什麼換條數據線，重開機幾次就能正常下載。雖然時好時壞。
擅長捉弄人的高木同學 第一季

duduru ***@***.***> 於 2024年9月23日 週一 下午10:46 寫道：

**Comment by hgalytoby** [comment]
> 不知道為什麼換條數據線，重開機幾次就能正常下載。雖然時好時壞。 擅長捉弄人的高木同學 第一季

此專案只要請求影片30沒回應就會重新嘗試請求資料，如果你在官方頁面上讀取超過30秒並且能看，那是我程式設計的問題。

如果官方都看不了了，那此專案肯定是無法下載的。

這跟數據線與重開機應該沒關係。

時好時壞應該是官方伺服器流量問題。

**Comment by garyshun** [comment]
不好意思，我想下載空之境界全十集，但進度一直是0%，然後當我點"從清單及硬碟中刪除"時，過了一陣子，他出現一個大概30000kB的檔案，但類型是DOWNLOAD檔案而不是MP4

**Comment by hgalytoby** [comment]
> 不好意思，我想下載空之境界全十集，但進度一直是0%，然後當我點"從清單及硬碟中刪除"時，過了一陣子，他出現一個大概30000kB的檔案，但類型是DOWNLOAD檔案而不是MP4

我今天嘗試下載了一下並沒有問題，你那邊的環境可以在官網上看影片嗎？，如果能看影片基本上就能下載。

**Comment by garyshun** [comment]
啊，能下載了，今天突然好了，謝謝

**Comment by internet-coffee** [comment]
我也是卡0%，myself可在30s內播放，我用的是debug版本，原版也是卡0%
![image](https://github.com/user-attachments/assets/8c25f442-5f60-4efc-b778-a773fefd476e)

**Comment by hgalytoby** [comment]
> 我也是卡0%，myself可在30s內播放，我用的是debug版本，原版也是卡0% ![image](https://private-user-images.githubusercontent.com/108166303/395869005-8c25f442-5f60-4efc-b778-a773fefd476e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTE1MTAsIm5iZiI6MTczNDMxMTIxMCwicGF0aCI6Ii8xMDgxNjYzMDMvMzk1ODY5MDA1LThjMjVmNDQyLTVmNjAtNGVmYy1iNzc4LWE3NzNmZWZkNDc2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMTA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjQyZmMyZjE5MzlkNTg0MjFhOTFlZWRjZjEzNTBkMDE1OWM1NTcyZWM2N2FkZDIzMGJhOGEyMzU0MmVjNTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.74Zp_PR9GiaU7Z6l0I5hBaK2mvhCcPPBn2kQMmOVH70)

我剛測試了我這邊下載沒問題，不知道是不是你被防毒檔了。

**Comment by KEVIN970712** [comment]
> > 我也是卡0%，myself可在30s內播放，我用的是debug版本，原版也是卡0% ![image](https://private-user-images.githubusercontent.com/108166303/395869005-8c25f442-5f60-4efc-b778-a773fefd476e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTE1MTAsIm5iZiI6MTczNDMxMTIxMCwicGF0aCI6Ii8xMDgxNjYzMDMvMzk1ODY5MDA1LThjMjVmNDQyLTVmNjAtNGVmYy1iNzc4LWE3NzNmZWZkNDc2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMTA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjQyZmMyZjE5MzlkNTg0MjFhOTFlZWRjZjEzNTBkMDE1OWM1NTcyZWM2N2FkZDIzMGJhOGEyMzU0MmVjNTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.74Zp_PR9GiaU7Z6l0I5hBaK2mvhCcPPBn2kQMmOVH70)
> 
> 我剛測試了我這邊下載沒問題，不知道是不是你被防毒檔了。

我只有用windows defender，今晚關掉再試試

**Comment by internet-coffee** [comment]
> > 我也是卡0%，myself可在30s內播放，我用的是debug版本，原版也是卡0% ![image](https://private-user-images.githubusercontent.com/108166303/395869005-8c25f442-5f60-4efc-b778-a773fefd476e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTE1MTAsIm5iZiI6MTczNDMxMTIxMCwicGF0aCI6Ii8xMDgxNjYzMDMvMzk1ODY5MDA1LThjMjVmNDQyLTVmNjAtNGVmYy1iNzc4LWE3NzNmZWZkNDc2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwMTA2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjQyZmMyZjE5MzlkNTg0MjFhOTFlZWRjZjEzNTBkMDE1OWM1NTcyZWM2N2FkZDIzMGJhOGEyMzU0MmVjNTUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.74Zp_PR9GiaU7Z6l0I5hBaK2mvhCcPPBn2kQMmOVH70)
> 
> 我剛測試了我這邊下載沒問題，不知道是不是你被防毒檔了。

有了感謝 允許MyselfAnime.exe通過防火牆即可
![image](https://github.com/user-attachments/assets/7426b0b5-87d2-4f9d-a3be-a261ac0d8839)
![image](https://github.com/user-attachments/assets/9b09a2d8-de90-4248-935b-d71fd6c60d7d)

**Comment by Tenyu86** [comment]
大大您好，我一般在使用下載器的時候很正常，可是會有某些集數一直卡在固定的下載進度(如圖)
我有試過把該集相關的檔案刪掉重新開機也沒用，想知道是什麼問題？
<img width="1022" height="532" alt="Image" src="https://github.com/user-attachments/assets/22be4426-1d1c-47e7-a5ff-4681a07e3eaa" />

**Comment by hgalytoby** [comment]
> 大大您好，我一般在使用下載器的時候很正常，可是會有某些集數一直卡在固定的下載進度(如圖) 我有試過把該集相關的檔案刪掉重新開機也沒用，想知道是什麼問題？ <img alt="Image" width="1022" height="532" src="https://private-user-images.githubusercontent.com/182064024/567521421-22be4426-1d1c-47e7-a5ff-4681a07e3eaa.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzQyNDQ1NDgsIm5iZiI6MTc3NDI0NDI0OCwicGF0aCI6Ii8xODIwNjQwMjQvNTY3NTIxNDIxLTIyYmU0NDI2LTFkMWMtNDdlNy1hNWZmLTQ2ODFhMDdlM2VhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMyM1QwNTM3MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMmQ0NjQ3NDk1YTAwOWU1NzM1OGIxYzdiNDM1YmJkYjMxNDY4MDk1Yjk5ZjM2YWFhMmU5YWY1YzAxZmQ3MzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ixywOoTH6KUJiPizdpAegB7Yymg3XdjniYL_BPg_ytw">

我在官網上看了命運10話跟玲音13話也會卡住，這應該是官網的問題，不如你在官網看看?如果你也是不能從頭看到尾那就是片源的問題

**Comment by Tenyu86** [comment]
那應該是官網的問題了，謝謝答覆
