### ISSUE TITLE
關於下載方面的小建議

### ISSUE THREAD

**Issue by Garytang01** [hgalytoby/MyselfAnimeDownloader#15]
希望可以在可下載途中的影片更改其他副檔名以區分,
和 下載清單的位置上方可以按下用排序方式分先後次序,  謝

![image](https://user-images.githubusercontent.com/33490277/133837598-05e76372-da16-4a2a-87d5-c3c4189f126d.png)

**Comment by hgalytoby** [comment]
> 希望可以在可下載途中的影片更改其他副檔名以區分,
> 和 下載清單的位置上方可以按下用排序方式分先後次序, 謝
> 
> ![image](https://user-images.githubusercontent.com/33490277/133837598-05e76372-da16-4a2a-87d5-c3c4189f126d.png)

1.更改其他副檔名是什麼意思?不太了解，目前是下載某個動漫會新增一個動漫資料夾，並依照網站上面的名字作為檔案名字，頂多改成下載前跳出一個視窗詢問要不要改檔名這類的，沒辦法做到下載途中改名字。

2.排先後次序是什麼意思? 這個我可能沒辦法改，因為我當初設計是越上面動漫會優先下載，可能一按排序下去整個下載優先順序就垮了。

**Comment by XCI9** [comment]
他的意思應該是下載前副檔名預設不要是.mp4，而用.mp4download或是其他自訂副檔名，下載完成後再改為.mp4
這樣在檔案總管可以直接區分哪些已經下載完畢，也不會誤開正在下載的檔案

**Comment by hgalytoby** [comment]
> 他的意思應該是下載前副檔名預設不要是.mp4，而用.mp4download或是其他自訂副檔名，下載完成後再改為.mp4
> 這樣在檔案總管可以直接區分哪些已經下載完畢，也不會誤開正在下載的檔案

原來是這樣r，那我會進行修改der。

**Comment by hgalytoby** [comment]
我這次更新將未下載完的影片副檔名改成 .download 了。

關於排序的問題目前沒打算處理。

如沒有其他問題，後續我會關閉此問題。

如還有其他問題請再告知，謝謝您。
