### ISSUE TITLE
程式會自行關閉

### ISSUE THREAD

**Issue by cs1224** [hgalytoby/MyselfAnimeDownloader#16]
如題，我把程式打開放著下載，然後他就不見了。

**Comment by hgalytoby** [comment]
> 如題，我把程式打開放著下載，然後他就不見了。

我只有幾個推測

最新的版本我今天更新的，我只有測幾個小時，不知道是不是此次原因。

如果你有用過之前的版本且不會有這種事情發生，那就會是我新版的問題了。

如果你是 windows 會不會跑到右下角去了?

**Comment by hgalytoby** [comment]
我掛著測試下載了81集動漫沒發生什麼事情，如再有發生，請記得一下是怎麼操作的，不然就是我做一個 Debug 版本了。

**Comment by cs1224** [comment]
你好，我是用筆電連usb接手機網路。有幾次是我同時更新遊戲和下載，然後程式就不見了；另外幾次是下載中我開網頁(跑很慢)瀏覽或看影片，程式就不見了。
我有確認過，是程式直接關掉，不是在右下角。
我再看看會不會是我自己電腦的問題

**Comment by hgalytoby** [comment]
> 你好，我是用筆電連usb接手機網路。有幾次是我同時更新遊戲和下載，然後程式就不見了；另外幾次是下載中我開網頁(跑很慢)瀏覽或看影片，程式就不見了。
> 我有確認過，是程式直接關掉，不是在右下角。
> 我再看看會不會是我自己電腦的問題

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Debug

你是 windows 嗎?

如果不是請再說一下。

用這個版本打開程式會多一個小黑窗。

如果出錯了小黑窗會有訊息。

再將訊息貼給我。

謝謝。

**Comment by cs1224** [comment]
我用慢速、一般，3個下載中還滿穩定的。
然後我調成高速、星爆，6個下載中程式就會自己關掉。 小黑窗也會一起。
不過我故意設定之後有抓到訊息
Traceback (most recent call last):
  File "myself_thread.py", line 267, in run
  File "myself_thread.py", line 260, in get_m3u8_data
IndexError: list index out of range

**Comment by hgalytoby** [comment]
> 我用慢速、一般，3個下載中還滿穩定的。
> 然後我調成高速、星爆，6個下載中程式就會自己關掉。 小黑窗也會一起。
> 不過我故意設定之後有抓到訊息
> Traceback (most recent call last):
> File "myself_thread.py", line 267, in run
> File "myself_thread.py", line 260, in get_m3u8_data
> IndexError: list index out of range

好的，看這個錯誤我大概知道問題了。

順便想了解一下你下載哪個動漫?

我也試試看去觸發，這樣我能更精準地解決問題。

**Comment by cs1224** [comment]
我是在抓物語系列的，還有一些比較冷門比較舊的，14、15年的

**Comment by hgalytoby** [comment]
> 我是在抓物語系列的，還有一些比較冷門比較舊的，14、15年的

我修好了。

今天晚上有空我就會上傳新版本。

原來這個 Bug 是我去年上傳就有了，難怪有時候影片下載會卡住不動，機率很大就是這個。

這段程式碼是取得影片資訊的跟我下載影片部分程式碼是一樣的，只是這邊取得影片資訊報錯了程式會直接掛掉，下載影片那邊程式不會掛掉反而是永遠不動了。

**Comment by hgalytoby** [comment]
我更新好了 ver 1.1.6

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.6

如果還有問題，請再告知。

謝謝。

**Comment by cs1224** [comment]
好的，感謝你。
辛苦了!
