### ISSUE TITLE
Thanks for sharing

### ISSUE THREAD

**Issue by WeiChihChern** [hgalytoby/MyselfAnimeDownloader#17]
你好, 謝謝你分享你的code

我在Apple Silicon上跑app過一陣子後會當掉app閃退且Qt似乎還沒支援apple silicon, 但我基於你的幾個function寫了一個cli的版本, 並且用ffmpeg下載影片檔。

因為我對前端的東西不太了解, 我很好奇你是怎麼知道要把抓到的網址加上vpx的呢(還有其他的處理)？沒有你的看你的code的話我應該找不到影片網址... Thanks!

**Comment by hgalytoby** [comment]
> 你好, 謝謝你分享你的code
> 
謝謝你的謝謝。

---

> 我在Apple Silicon上跑app過一陣子後會當掉app閃退且Qt似乎還沒支援apple silicon, 但我基於你的幾個function寫了一個cli的版本, 並且用ffmpeg下載影片檔。
> 
Apple Silicon 指的是 M1 嗎？

我的 Mac 是 M1 ，我用我的 Mac 開著程式但沒有下載影片，掛著好幾個小時都沒有閃退或當掉的問題。

但實際上不管是 Windwos、Linux、Mac，我只有在開發的時候會開著程式測試，除此之外我都沒開著一小時以上甚至不到半小時。

所以我也不清楚 Mac 如何觸發當掉的情形，我也不會拿 Mac 下載影片，因為沒什麼容量可以放了。

我覺得用 ffmpeg 下載影片比較好，但當初我的想法是能邊載邊看，我也沒有影片 header 的概念，就用 `with open 'w'` 方式去續寫影片了。

---

> 因為我對前端的東西不太了解, 我很好奇你是怎麼知道要把抓到的網址加上vpx的呢(還有其他的處理)？

你只要會爬蟲或者會寫後端 Api 給前端用，就會我是如何知道網址要加 `vpx` 的問題了，你指的其他處理是指哪些處理呢？

---

>沒有你的看你的code的話我應該找不到影片網址... Thanks!

這邊你是想說: `沒有看你的code的話我應該找不到影片網址... Thanks!` 嗎？

**Comment by WeiChihChern** [comment]
對是Ｍ1。我第一次使用也是掛了7 or 8個小時, 但突然閃退。 之後app就打不開了, 我要刪除再複製到application一次才能再開。 也許是我選星爆, 同時下載又選很高(50), 選好集數點選下載後就跑彩虹圈圈了, 但有繼續在下載, 只是app一直跑彩虹圈圈。

> 我覺得用 ffmpeg 下載影片比較好，但當初我的想法是能邊載邊看，我也沒有影片 header 的概念，就用 with open 'w' 方式去續寫影片了。

了解, 另一點我感覺用ffmpeg下載好像也比較快一些


> 你只要會爬蟲或者會寫後端 Api 給前端用，就會知道我是如何知道網址要加 vpx 的問題了，你指的其他處理是指哪些處理呢？
> 
> Myself 網站拿影片的流程是這樣的:
> 
> 點擊影片 -> 發送 Api 取得 Host 資料 -> 基於 Host 資料取得 m3u8 資料 -> 基於 m3u8 資料取得影片。

謝謝你的解說XD 我的確也是對爬蟲這塊不了解 所以沒有看你的code的話根本不知道怎麼找到網址。 Myself這個方式是不是有點算在隱藏m3u8的網址？ 就沒辦法直接在html上找到, 好像現在很多網站都會像這樣試著隱藏影片網址對嗎？

**Comment by hgalytoby** [comment]
> 對是Ｍ1。我第一次使用也是掛了7 or 8個小時, 但突然閃退。 之後app就打不開了, 我要刪除再複製到application一次才能再開。 也許是我選星爆, 同時下載又選很高(50), 選好集數點選下載後就跑彩虹圈圈了, 但有繼續在下載, 只是app一直跑彩虹圈圈。

我沒試過同時下載 50 又選星爆這樣不太好。

這樣有點像在攻擊伺服器了！

這樣算下來你是 50 * 10  = 500 => 一次發 500個請求，我不建議這麼做，哪天網站倒了就沒得看沒得載了。

我不知道你的網路速度多快，通常同時下載設定不要超過 10 比較好。

> 了解, 另一點我感覺用ffmpeg下載好像也比較快一些 

我不知道 `ffmpeg` 的下載模式是什麼，因為我的星爆設定是一次最多10個連接，所以假設有 100 個 ts 檔案，最大是一次下載10個，那如果 `ffmpeg` 是你丟了 `m3u8 url` 就一次載 100 個 ts 的話，確實會比我的還要快。 

> 謝謝你的解說XD 我的確也是對爬蟲這塊不了解 所以沒有看你的code的話根本不知道怎麼找到網址。 可以麻煩您稍微解釋一下vpx到底是什麼嗎？我好有點頭緒在google上找一些教學。 Myself這個方式是不是有點算在隱藏m3u8的網址？ 就沒辦法直接在html上找到, 好像現在很多網站都會像這樣試著隱藏影片網址對嗎？

我覺得 Myself 並沒有藏 m3u8 ，只要懂一點的都可以在 F12 Network 那邊看到。

第一步爬這個頁面集數的 `Api Url`
![image](https://user-images.githubusercontent.com/50397689/135570561-b4441f63-023d-42d9-8aa1-04bdab1776fb.png)

第二步按 `F12` 點選 `Network` 選擇 `fetch/XHR` 之後去點擊集數跳出影片播放頁面，就可以看到 Myself 往哪裡發送請求了。
![image](https://user-images.githubusercontent.com/50397689/135570761-f2d35d4a-d77a-4aa8-a353-226fba281ca0.png)

第三步點選 Preview 可以看到回傳的 `json` 格式，就是在這邊拿到 `vpx`的。
![image](https://user-images.githubusercontent.com/50397689/135570862-7dfc842f-b072-43bc-9226-92951c7b1312.png)

第四步觀察 `m3u8` 的網址。
![image](https://user-images.githubusercontent.com/50397689/135570977-755b2a73-3178-4af6-aa54-67e45c40ba71.png)

第五步寫程式下載，整個程式核心就在這邊而已，其餘都是 `Qt` 串一串弄成 `GUI` 而已。
