### ISSUE TITLE
開始下載時會閃退

### ISSUE THREAD

**Issue by yue8597114** [hgalytoby/MyselfAnimeDownloader#18]
有登入也有更新 版本1.1.6 下載速度是星爆 連接5 10/23時用是正常的 不知道問題出在哪

**Comment by yue8597114** [comment]
myself網站有開著

**Comment by hgalytoby** [comment]
> 有登入也有更新 版本1.1.6 下載速度是星爆 連接5 10/23時用是正常的 不知道問題出在哪

下載動畫不需要登入，現在下載R18好像也不需要了。

你同時下載是5個嗎?

你的系統是什麼?

依照你的敘述，你是從10/23使用時下載沒問題，然而現在要下載動漫點擊開始下載後就會閃退就是了?

你可以嘗試重新下載程式看看。

如果還有發聲請再告知，在做進一步的調查，謝謝。

**Comment by yue8597114** [comment]
> > 有登入也有更新 版本1.1.6 下載速度是星爆 連接5 10/23時用是正常的 不知道問題出在哪
> > 下載動畫不需要登入，現在下載R18好像也不需要了。
> 
> 你同時下載是5個嗎?
> 
> 你的系統是什麼?
> 
> 依照你的敘述，你在10/23使用時下載沒問題，然而現在要下載動漫，點擊開始下載後就會閃退就是了?
> 
> 你可以嘗試重新下載程式看看。
> 
> 如果還是一樣會閃退請再告知，在做進一步的調查，謝謝。
> 
> > myself網站有開著
> 
> 這個開著沒關係。

今天重新下載後就正常了 謝謝 我的系統是win10 home 同時下載數5

**Comment by hgalytoby** [comment]
> 今天重新下載後就正常了 謝謝 我的系統是win10 home 同時下載數5

如果問題一直出現我在弄一個 Debug 版本，這樣好找問題。

**Comment by hgalytoby** [comment]
我不知道您還有沒有遇到問題或者在用。

如果還有其他問題請在發問。

謝謝您。
