### ISSUE TITLE
程式只要縮小就會自動隱藏

### ISSUE THREAD

**Issue by oLizxo** [hgalytoby/MyselfAnimeDownloader#21]
如題
我還有一個問題就是
下載後的影片不知為何只要快速移動進度條就會卡頓
我的版本是window 10  ver1.1.6

**Comment by hgalytoby** [comment]
> 如題 我還有一個問題就是 下載後的影片不知為何只要快速移動進度條就會卡頓 我的版本是window 10 ver1.1.6

1.你可以在設定 -> 取消最小化至狀態列。

2.影片問題，我猜是因為我合併影片的方式不是使用正規的方式合併，所以才導致會有卡頓的情況。

剛剛我下載發現我 windows 版本好像沒弄好，一直跳出作者更新了，好像是我忘了改版號了ㄏ。

**Comment by oLizxo** [comment]
> > 如題 我還有一個問題就是 下載後的影片不知為何只要快速移動進度條就會卡頓 我的版本是window 10 ver1.1.6
> 
> 1.你可以在設定 -> 取消最小化至狀態列，這樣就不會隱藏了。
> 已解決
> 2.影片卡頓是指移動進度條後，聲音會先出來但是畫面不會動，之後影片才會正常是嗎？
> 對 我的狀況是這樣 那我需要做什麼處理嘛

**Comment by hgalytoby** [comment]
> > 2.影片卡頓是指移動進度條後，聲音會先出來但是畫面不會動，之後影片才會正常是嗎？
> > 對 我的狀況是這樣 那我需要做什麼處理嘛

你不用做什麼處理，這應該是我程式合併影片的問題，要解決這問題我需要改成 ffmpeg 合併影片，但我目前不打算修改，請見諒。

**Comment by oLizxo** [comment]
> > > 2.影片卡頓是指移動進度條後，聲音會先出來但是畫面不會動，之後影片才會正常是嗎？
> > > 對 我的狀況是這樣 那我需要做什麼處理嘛
> 
> 你不用做什麼處理，這應該是我程式合併影片的問題，要解決這問題我需要改成 ffmpeg 合併影片，但我目前不打算修改，請見諒。

好的謝謝您 那影片是只會卡頓而已不會有其他的問題嗎

**Comment by hgalytoby** [comment]
> > > > 2.影片卡頓是指移動進度條後，聲音會先出來但是畫面不會動，之後影片才會正常是嗎？
> > > > 對 我的狀況是這樣 那我需要做什麼處理嘛
> > 
> > 
> > 你不用做什麼處理，這應該是我程式合併影片的問題，要解決這問題我需要改成 ffmpeg 合併影片，但我目前不打算修改，請見諒。
> 
> 好的謝謝您 那影片是只會卡頓而已不會有其他的問題嗎

應該沒有其他問題，如果有其他問題請你再告知我。

**Comment by oLizxo** [comment]
好的 謝謝您

**Comment by hgalytoby** [comment]
你反應影片移動進度條問題後，我使用 Mac VLC 播放影片，就有你所謂的卡頓狀況。

但是我現在用 Windows PotPlayer 播放影片就沒有卡頓的問題了。

或許你可以嘗試換播放軟體。

**Comment by oLizxo** [comment]
> 你的影片反應移動進度條問題後，我有使用VLC播放影片，然後是你的卡頓。
> 我現在用 Windows PotPlayer 播放影片就沒有卡頓的問題了。
> 你可以試換播放軟體。
好的!! 我確認完畢是可以的 非常感謝
