### ISSUE TITLE
出現Failed to execute script main

### ISSUE THREAD

**Issue by oLizxo** [hgalytoby/MyselfAnimeDownloader#22]
在下載的過程中突然出現Failed to execute script main的視窗
然後就打不開應用程式了 不知道是甚麼原因
版本式ver.1.1.6
![螢幕擷取畫面 2022-06-19 14 20 04](https://user-images.githubusercontent.com/107144035/174468614-566be83e-cc5f-4d46-b827-d079705b1426.png)

**Comment by hgalytoby** [comment]
> 在下載的過程中突然出現Failed to execute script main的視窗 然後就打不開應用程式了 不知道是甚麼原因 版本式ver.1.1.6 ![螢幕擷取畫面 2022-06-19 14 20 04](https://user-images.githubusercontent.com/107144035/174468614-566be83e-cc5f-4d46-b827-d079705b1426.png)

曾經有人反應過這個問題，但我也不知道為什麼會這樣，最後解法好像都是重新下載。

**Comment by oLizxo** [comment]
> > 在下載的過程中突然出現Failed to execute script main的視窗 然後就打不開應用程式了 不知道是甚麼原因 版本式ver.1.1.6 ![螢幕擷取畫面 2022-06-19 14 20 04](https://user-images.githubusercontent.com/107144035/174468614-566be83e-cc5f-4d46-b827-d079705b1426.png)
> 
> 曾經有人反應過這個問題，但我也不知道為什麼會這樣，最後解法好像都是重新下載。
> 
> [點此連結](https://github.com/hgalytoby/MyselfAnimeDownloader/issues/9#issuecomment-824053120)

那我需要把整個程式重新下載還是把MyselfAnime + 我下載的動漫資料夾以外都刪掉重新執行

**Comment by hgalytoby** [comment]
> > > 在下載的過程中突然出現Failed to execute script main的視窗 然後就打不開應用程式了 不知道是甚麼原因 版本式ver.1.1.6 ![螢幕擷取畫面 2022-06-19 14 20 04](https://user-images.githubusercontent.com/107144035/174468614-566be83e-cc5f-4d46-b827-d079705b1426.png)
> > 
> > 
> > 曾經有人反應過這個問題，但我也不知道為什麼會這樣，最後解法好像都是重新下載。
> > [點此連結](https://github.com/hgalytoby/MyselfAnimeDownloader/issues/9#issuecomment-824053120)
> 
> 那我需要把整個程式重新下載還是把MyselfAnime + 我下載的動漫資料夾以外都刪掉重新執行

你可以先試試看刪除 MyselfAnime.exe 就好。

那個動漫資料夾應該不用刪除。

**Comment by oLizxo** [comment]
只刪掉MyselfAnime.exe在重新下載好像不行

**Comment by hgalytoby** [comment]
> 只刪掉MyselfAnime.exe在重新下載好像不行

你先試試看將 MyselfAnimeDownload 重新壓縮到新的資料夾看能不能運行。

**Comment by oLizxo** [comment]
如果是將壓縮檔移動到其他資料夾是可以運行的
但是之前的下載資料就沒有了 相當於再下載一個ver1.1.6

如果把那些資料重新壓縮並移動到其他資料夾也沒辦法

**Comment by hgalytoby** [comment]
> 剛剛看到資料夾好像有多這個檔案user.json 如果是將壓縮檔移動到其他資料夾是可以運行的 但是之前的下載資料就沒有了 相當於再下載一個ver1.1.6
> 
> 如果把那些資料重新壓縮並移動到其他資料夾也沒辦法

你應該只需要保留曾經下載過的動漫資料夾，其餘都可以刪除，設定檔重新再設定就行了。

**Comment by oLizxo** [comment]
> > 剛剛看到資料夾好像有多這個檔案user.json 如果是將壓縮檔移動到其他資料夾是可以運行的 但是之前的下載資料就沒有了 相當於再下載一個ver1.1.6
> > 如果把那些資料重新壓縮並移動到其他資料夾也沒辦法
> 
> 你應該只需要保留曾經下載過的動漫資料夾，其餘都可以刪除，設定檔重新再設定就行了。
> 
> 不過如果這麼做，要記得將尚未下載完成的動漫進行刪除。
> 
> 如果這樣的操作你能接受，所以你的動作應該是:
> 
> 重新解壓縮一個新的 MyselfAnimeDownload 後，打開程式將下載位置資料夾設定到之前設定的下載資料夾位置，這樣就行了。

好的 我試試看

**Comment by oLizxo** [comment]
重新用了之後是可以下載的 非常感謝
