### ISSUE TITLE
無法執行

### ISSUE THREAD

**Issue by keniony** [hgalytoby/MyselfAnimeDownloader#25]
![未命名](https://user-images.githubusercontent.com/112224504/187010076-5ae0f4f5-98c5-4ae4-af8b-26a2c0c0e28c.png)

**Comment by hgalytoby** [comment]
參考

https://github.com/hgalytoby/MyselfAnimeDownloader/issues/22
https://github.com/hgalytoby/MyselfAnimeDownloader/issues/9

**Comment by keniony** [comment]
ok 可以執行了 感謝

**Comment by hgalytoby** [comment]
如果還有其他問題，請在發問，謝謝。
