### ISSUE TITLE
在Mac上無法打開main 

### ISSUE THREAD

**Issue by 0128807** [hgalytoby/MyselfAnimeDownloader#3]
https://user-images.githubusercontent.com/77901808/105615267-468fa600-5d9d-11eb-880e-e835a4e1cd27.mov

我已經在安全性和隱私性上允許打開main，但是我仍然無法打開它，我等待了10分鐘，但是仍然沒有任何反應, 是我做錯了什麼嗎

**Comment by 0128807** [comment]
我也下載了MyselfAnimeDownloader-master文件

**Comment by hgalytoby** [comment]
https://user-images.githubusercontent.com/50397689/105617157-497bac80-5e18-11eb-9712-dedcc8104163.mov

**Comment by hgalytoby** [comment]
> 我也下載了MyselfAnimeDownloader-master文件

我只有自己 Ｍac 可以測試

晚點我朋友起床我請我朋友幫我測試看看

請問你是下載 ver 1.0.3的嗎？

**Comment by hgalytoby** [comment]
>  Screen.Recording.2021-01-23.at.5.03.38.PM.mov 
> 我已經在安全性和隱私性上允許打開main，但是我仍然無法打開它，我等待了10分鐘，但是仍然沒有任何反應, 是我做錯了什麼嗎

我只有自己 Ｍac 可以測試

晚點我朋友起床我請我朋友幫我測試看看

請問你是下載 ver 1.0.3的嗎？

**Comment by hgalytoby** [comment]
>  Screen.Recording.2021-01-23.at.5.03.38.PM.mov 
> 我已經在安全性和隱私性上允許打開main，但是我仍然無法打開它，我等待了10分鐘，但是仍然沒有任何反應, 是我做錯了什麼嗎

我剛下載 ver1.0.2 的看了一下

應該是我當初有打開後 main.app 後，在壓縮上傳的！

所以導致`路徑是我的電腦路徑`所以才出了問題，你改下載 1.0.3 的測試！

**Comment by hgalytoby** [comment]
> > Screen.Recording.2021-01-23.at.5.03.38.PM.mov
> > 我已經在安全性和隱私性上允許打開main，但是我仍然無法打開它，我等待了10分鐘，但是仍然沒有任何反應, 是我做錯了什麼嗎
> 
> 我剛下載 ver1.0.2 的看了一下
> 
> 應該是我當初有打開後 main.app 後，在壓縮上傳的！
> 
> 所以導致`路徑是我的電腦路徑`所以才出了問題，你改下載 1.0.3 的試試看！

**Comment by hgalytoby** [comment]
>  Screen.Recording.2021-01-23.at.5.03.38.PM.mov 
> 我已經在安全性和隱私性上允許打開main，但是我仍然無法打開它，我等待了10分鐘，但是仍然沒有任何反應, 是我做錯了什麼嗎

我剛下載 ver1.0.2 的看了一下 

發現是我以自己的 Mac 打開 main.app 後，測試能啟用在進行壓縮上傳的！

所以我推測是因為`路徑是我的電腦路徑`所以才出了問題，你改下載 1.0.3 的試試看！

不過我也更新了 1.0.2 的 mac 版本了！

不過還是推薦你下載最新的版本！

**Comment by 0128807** [comment]
還是不行, 1.0.2 和 1.0.3 都試過, 也把config.json 與 log資料夾刪除了

**Comment by hgalytoby** [comment]
> 還是不行, 1.0.2 和 1.0.3 都試過, 也把config.json 與 log資料夾刪除了

好的！等我研究好解決問題會馬上告知你！

**Comment by 0128807** [comment]
<img width="1440" alt="Screen Shot 2021-01-24 at 12 49 10 AM" src="https://user-images.githubusercontent.com/77901808/105622353-f76a6500-5dde-11eb-903d-fba30981b9f6.png">

開了變成這樣子

**Comment by hgalytoby** [comment]
正常的 開了會呈現那樣  那程式之後有運行出來嗎?

**Comment by 0128807** [comment]
没有

**Comment by hgalytoby** [comment]
> 没有

幫我下載這個  https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/test1

然後 在套件裡面 Contents -> MacOS ->  main 之後截圖給我看！

**Comment by 0128807** [comment]
<img width="1440" alt="Screen Shot 2021-01-24 at 12 49 10 AM" src="https://user-images.githubusercontent.com/77901808/105624607-24277800-5df1-11eb-897a-8a52e84bc76e.png">
再讓它跑嗎?

**Comment by hgalytoby** [comment]
> 没有

你有在測試那兩個新的檔案嗎?

 https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/test1

你的小黑窗 不應該是這樣 

想問一下 左下角的 Myself 那些 是不是有顯示出來了?

**Comment by 0128807** [comment]
它顯示有開啟，但沒有頁面顯示

**Comment by 0128807** [comment]
剛才試了另一個 開了直接退出

**Comment by hgalytoby** [comment]
> 它顯示有開啟，但沒有頁面顯示

所以  new 的依然打開來馬上退出

另一個小黑窗呢?

在這之前你說的 顯示有開啟沒有頁面

指的是  雖然右下角圖示有顯示 但依然頁面就是了?

**Comment by 0128807** [comment]
就是這樣
然後沒問題

**Comment by hgalytoby** [comment]
> 就是這樣
> 然後沒問題

確實在我朋友的 MAC 一樣打不開來 app 程式。

但是執行 main 的話 是可以執行程式的！

關於這個問題我星期一去公司嘗試解決看看！

如果 OK 再通知你！

**Comment by 0128807** [comment]
好的謝謝！

**Comment by hgalytoby** [comment]
> 好的謝謝！

應該解決問題了!

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/MacTest

請幫我把 MyselfAnime.app 放到應用程式資料夾!

如果不知道在哪裡應用程式資料夾在哪裡，查看我附的圖!

如果不照著做會無法啟動 MyselfAnime.app!

**Comment by 0128807** [comment]
可以了! 非常感謝!

**Comment by hgalytoby** [comment]
> 可以了! 非常感謝!

不用客氣!

你也幫到我了!

最終原因是因為 Mac 最新版 11 會打不開程式，我的 Mac 還在10 版所以一直都沒有問題，所以我才沒有發現新版的問題。
