### ISSUE TITLE
新版无法取得MyselfAnime 网站资料

### ISSUE THREAD

**Issue by anshutdown** [hgalytoby/MyselfAnimeDownloader#31]
https://myself-bbs.com/ 网页可以直接打开，旧版的也可以用

**Comment by hgalytoby** [comment]
不太懂。

你指的是開啟程式卻打不開嗎？

還是打開程式沒資料顯示？？

能的話附上幾張圖，謝謝。

**Comment by anshutdown** [comment]
之前 运行 python main.py 的方式运行 新版 没问题，
但是卡进度条了。

之后我再通过指定 python main.py 就提示 无法连接资料站
不确定是否因为vpn的原因

**Comment by anshutdown** [comment]
![image](https://user-images.githubusercontent.com/26587612/190978676-49d749ab-5de5-416a-8899-5e0073bbcbe1.png)
这是新版之前的卡进度条

**Comment by anshutdown** [comment]
![image](https://user-images.githubusercontent.com/26587612/190979067-727d2b75-909f-4033-a28d-9c2b6ab35fa7.png)

**Comment by anshutdown** [comment]
VPN 没有打开，网站正常访问的，旧版正常使用，新版提示报错以及 无法连接

**Comment by anshutdown** [comment]
![image](https://user-images.githubusercontent.com/26587612/190980010-4455452b-04e9-4a95-94f2-fa78be50d1d1.png)

1.1.7 与1.1.8 应该没有冲突吧？
1.1.7 很稳定，但是缺少了搜索的功能
大神，辛苦你了帮我看下是什么原因。
少了搜索功能挺难受的

**Comment by anshutdown** [comment]
> 

大佬 图片已经补充

**Comment by hgalytoby** [comment]
> ![image](https://user-images.githubusercontent.com/26587612/190979067-727d2b75-909f-4033-a28d-9c2b6ab35fa7.png)

我看這個圖片有發現 Log 資料夾找不到 undone 檔案。

你有將之前 1.1.7 的 Log 放到 1.1.8嗎？

**Comment by anshutdown** [comment]
原本 设置的是下载的文件夹是 1.1.7的根目录。
现在我把目录中的 image Log config.json myselfAnime 都单独拿出来了
现在下载目录是算干净的，
1.1.8 的文件是新下载的
![image](https://user-images.githubusercontent.com/26587612/191140845-792448c2-6e13-4fe5-9a3d-840aeaac5c75.png)

这个刚刚 产生的錯誤訊息圖

Ps: 我重启应用就好了
![image](https://user-images.githubusercontent.com/26587612/191141365-0fc5c68b-7d8e-4989-8d2c-c2fc731e8cec.png)

感谢大神给的有用的建议！！

**Comment by anshutdown** [comment]
![image](https://user-images.githubusercontent.com/26587612/191142378-828deede-6fe6-4125-8cbb-5cb5dfd068bb.png)

搜索不到东西？为什么我一搜索 就会闪退

**Comment by anshutdown** [comment]
![image](https://user-images.githubusercontent.com/26587612/191142586-9b0d7c2c-cd16-45f3-95b3-ea6c96aed8c0.png)
不搜索也会闪退。。。。。。。

**Comment by anshutdown** [comment]
大神  我需要你帮助，，，

**Comment by hgalytoby** [comment]
我剛剛看了搜尋的程式碼知道了問題點了。

還有你一打開就閃退的問題，看起來是你那邊的網路在當下那次請求失敗我沒有防呆而導致閃退。

今天下班我回家再改版本。

我現在這邊時間快早上9點，晚上我才能改好。

**Comment by anshutdown** [comment]
感谢！大神的回复

**Comment by hgalytoby** [comment]
我放了新版本，所有請求都加防呆了。

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.9

不過我好奇為什麼1.1.7你就不會有這問題呢?

我只有加搜尋功能與修錯誤，也沒更新套件版本。

**Comment by anshutdown** [comment]
1.1.7 正常使用是没有任何问题的，
所以我也纳闷， 或许是因为公司网络吧？
PS 你的摸鱼神器真好用。感谢大佬的帮助

**Comment by hgalytoby** [comment]
> 1.1.7 正常使用是没有任何问题的， 所以我也纳闷， 或许是因为公司网络吧？ PS 你的摸鱼神器真好用。感谢大佬的帮助

1.1.7 能在公司用嗎?

**Comment by anshutdown** [comment]
一般電腦都是不關機的，就是可能一周或者2周關掉一次，然後myself 一直運行在後臺的。
之前1.1.7 使用的話，沒有任何問題的哦

**Comment by anshutdown** [comment]
下載列表上，點擊已完成清除，
導致了閃退，再次 運行python main.py
提示這個
![image](https://user-images.githubusercontent.com/26587612/191634259-98998312-77ad-42de-a596-701e45525b26.png)

**Comment by hgalytoby** [comment]
> 一般電腦都不關機的，就是可能一周或者2周關掉一次，然後myself 一直運行在後臺的。 之前1.1.7 使用的話，沒有任何問題的哦

剛看了一下 commit 紀錄，確實沒有改關於請求套件版本的紀錄。

真不知道是什麼問題。

> 下載列表上，點擊已完成清除， 導致了閃退，再次 運行python main.py 提示這個 ![image](https://user-images.githubusercontent.com/26587612/191634259-98998312-77ad-42de-a596-701e45525b26.png)

我回家在修復。

**Comment by anshutdown** [comment]
下載目錄中沒有提示這個第七話在下載中，但是該番文件夾確實顯示這個番第七話沒有下載成功。
![image](https://user-images.githubusercontent.com/26587612/191634750-a6753012-02f2-4245-b5d5-927da1b1e319.png)

**Comment by hgalytoby** [comment]
有沒有點擊已完成清除的報錯訊息。

**Comment by anshutdown** [comment]
![image](https://user-images.githubusercontent.com/26587612/191642696-a0d95d33-45cb-4ac2-9c96-06af60c5b009.png)
这应该是报错信息了

**Comment by anshutdown** [comment]
之后 直接闪退了 再后面我重新运行 就是另外的报错了

**Comment by hgalytoby** [comment]
> 之后 直接闪退了 再后面我重新运行 就是另外的报错了

ok，這就足夠了。

**Comment by hgalytoby** [comment]
雖然知道你的報錯了...

但我不知道怎麼觸發，我也跟你一樣下載美少女大叔，然後按清除已完成，並沒有問題。

我目前看程式碼也沒發現為什麼你按下去時會有 KeyError 的問題。

你還有什麼操作嗎?

**Comment by anshutdown** [comment]
@hgalytoby  我的推测是因为，文件没有下载完成 还处在 .download 状态 此时点击 清除 1.1.8的下载列表 就会导致报错闪退。
然后对于该文件的状态  为何下载列表中没有显示 “正在下载”的状态 而显示已下载。
我也只能猜测 也许我来回使用 1.1.7和1.1.8吧？总之 1.1.8那个包已经打不开了 需要删掉重新下载新的包
1.1.9 可以用 没有问题

**Comment by anshutdown** [comment]
我觉得这是偶然性的，可以忽略，但是清空列表这里的报错 太致命了。直接会导致程序挂掉
可以优化一下吗？

**Comment by hgalytoby** [comment]
> 我觉得这是偶然性的，可以忽略，但是清空列表这里的报错 太致命了。直接会导致程序挂掉 可以优化一下吗？

我昨晚有激烈操作一番，有發現幾個隱藏 Bug，我已經修好了，我擔心有我這一修下去會導致其餘的地方報出 Bug，我可以先給你改好的程式碼，你繼續用如果還有 Bug 我繼續修，在那之前我就先不發新版本，這樣 ok 嗎？

**Comment by anshutdown** [comment]
没问题，你可以先发我邮箱
1241252886@qq.com
有问题我会及时反馈你

**Comment by hgalytoby** [comment]
> 没问题，你可以先发我邮箱 [1241252886@qq.com](mailto:1241252886@qq.com) 有问题我会及时反馈你

你應該都是 run main.py 對吧？ 我直接 push 上來你 clone 就可以了如何？

**Comment by anshutdown** [comment]
可以 你先放dev分支吧？

**Comment by hgalytoby** [comment]
> 可以 你先放dev分支吧？

可以，正有此打算！

我晚上開一個分支，好了會通知你。

謝謝。

**Comment by hgalytoby** [comment]
> 可以 你先放dev分支吧？

https://github.com/hgalytoby/MyselfAnimeDownloader/tree/debug

我自己有測試了，但還沒發現問題，拜託你了謝謝。

**Comment by anshutdown** [comment]
![image](https://user-images.githubusercontent.com/26587612/194440856-0285f276-84bf-45dd-bcf4-567d6bc85454.png)
大佬  无论搜索什么都提示这个。。虽然不会闪退 但是搜索功能好像没有了

**Comment by anshutdown** [comment]
打开后第一次搜索 也是提示这个

**Comment by hgalytoby** [comment]
> 打开后第一次搜索 也是提示这个

可能真的無法搜尋，不然就是你那邊的網路我用程式無法拿到網頁資料。

要解決網路這個問題，就是我架一個 API Server ，程式發請求找我的 API Server 拿資料，我的 API Server 去拿 MyselfAnime 資料，最後再回傳給程式了。

**Comment by hgalytoby** [comment]
這是我用公司電腦搜尋的結果

![image](https://user-images.githubusercontent.com/50397689/194443628-a1a8b9bb-c43c-4068-877f-77ed7f14fb2a.png)

![image](https://user-images.githubusercontent.com/50397689/194443638-3301713e-d03f-46a8-b694-bfdddfb461df.png)

**Comment by hgalytoby** [comment]
你試試看這個網頁能不能看到資料？

這是別人的 API

https://myself-bbs.jacob.workers.dev/search/%E9%8A%80%E9%AD%82
