### ISSUE TITLE
取得資料一直失敗(因官方更新拿影片的方式)

### ISSUE THREAD

**Issue by yanghao758** [hgalytoby/MyselfAnimeDownloader#32]
不知道為甚麼一直卡在取得資料中(失敗n次)

**Comment by hgalytoby** [comment]
> 不知道為甚麼一直卡在取得資料中(失敗n次)

因為官方改下載方式了，現在的版本是無法下載影片的。

**Comment by hgalytoby** [comment]
> 那請問是不是不會再更新版本了?我有看見網站說因為myself要關站，所以程式不會再更新。本來打算把想看的動畫下載備份一下。
> 
> > > 不知道為甚麼一直卡在取得資料中(失敗n次)
> > 
> > 
> > 因為官方改拿影片的方式了，現在的版本是無法下載影片的。

可以暴力修好，但要看多少人需要。

**Comment by yanghao758** [comment]
了解了感謝大大

**Comment by hgalytoby** [comment]
@yanghao758  @victorgithub71 現在官方改回原本的方式了，你現在應該能下載了。

**Comment by victorgithub71** [comment]
可以下載了，謝謝。

**Comment by yanghao758** [comment]
我也可以了，謝謝

**Comment by mjjjj21** [comment]
又不行了，大大求救

**Comment by hgalytoby** [comment]
> 又不行了，大大求救

因為又改回新影片的拿法了，所以不行下載了。

**Comment by hgalytoby** [comment]
我昨天已經有修好下載器了，但是並沒有優化程式碼，而且 0 點左右的時候官網改回舊的方式。

目前我不知道官方為什麼一下舊的一下新的，所以我目前還沒有要放上新的版本。

**Comment by mjjjj21** [comment]
好的，感謝大大我再去試一下

**Comment by mjjjj21** [comment]
可能現在官網用新的方式了

**Comment by ken1882** [comment]
建議可以開一支新的 branch 放上新的拿影片方法

**Comment by hgalytoby** [comment]
> 建議可以開一支新的 branch 放上新的拿影片方法

你只需要新的拿影片方法嗎？

**Comment by hgalytoby** [comment]
> 可能現在官網用新的方式了

現在 1.1.9 版本無法下載就是官方用新的拿影片方式。

因昨天本來官方晚上拿影片的方式變成 (原本 -> 新 -> 舊 -> 新)，所以我沒有更新程式上來給大家用。

**Comment by ken1882** [comment]
> > 建議可以開一支新的 branch 放上新的拿影片方法
> 
> 你意思是需要新的拿影片方法嗎？還是新的下載器也要？
> 
> 我可以更新 Share/myself.py。

ㄜ 看你啦
新的拿影片方法我有去看知道是改用 websocket 了 (也 fork 改成可下載的版本了，不過大部份舊番的節點都是死的也沒辦法在網站上看更別提載)

新下載器如果功能已經完成是可以開新的 branch (通常叫 preview/beta 之類的，或單純的 feature branch 也行) 推上來當程式備份
release 就看你想不想丟

**Comment by hgalytoby** [comment]
> ㄜ 看你啦 新的拿影片方法我有去看知道是改用 websocket 了 (也 fork 改成可下載的版本了，不過大部份舊番的節點都是死的也沒辦法在網站上看更別提載)
> 
> 新下載器如果功能已經完成是可以開新的 branch (通常叫 preview/beta 之類的，或單純的 feature branch 也行) 推上來當程式備份 release 就看你想不想丟


昨天有改用 websocket，玩了一下一次連接要求 m3u8 只能一次，拿完就被 close 了。

依照 m3u8 拿到 host ，如果沒拿到比較好的 host 會載很慢。

**Comment by mjjjj21** [comment]
我的python偏菜，有勞各位大大

**Comment by ssyang8426** [comment]
想下載動畫偏冷門QQ  希望可以有新的下載器可以用

**Comment by hgalytoby** [comment]
@ssyang8426 @mjjjj21 我剛剛已經修好了

如果大家願意請幫我按顆星星，謝謝。

**Comment by yanghao758** [comment]
我的還在失敗 好像還是不行QQ

**Comment by hgalytoby** [comment]
> 我的還在失敗 好像還是不行QQ

你下載 1.1.10 版本嗎?

**Comment by hgalytoby** [comment]
> 我的還在失敗 好像還是不行QQ

@yanghao758 

你下載 1.1.10 版本嗎?

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.10

**Comment by ssyang8426** [comment]
@hgalytoby 可以使用了，非常謝謝你的分享，辛苦了!! 星星已按出👍

**Comment by ssyang8426** [comment]
> 我的還在失敗 好像還是不行QQ

要使用1.1.10版本喔，今天我用1.1.9的就無法下載，稍早已經發出最新版本出來了，可以確認一下，對了防火牆也記得關掉再下載影片

**Comment by victorgithub71** [comment]
還失敗的話直接去myself看看可不可以線上觀看,發現好多動畫都死掉不能看了

**Comment by hgalytoby** [comment]
> 還失敗的話直接去myself看看可不可以線上觀看,發現好多動畫都死掉不能看了

只要官網無法觀看就代表下載器也無法下載。

**Comment by mjjjj21** [comment]
星星已給，謝謝大大
