### ISSUE TITLE
影片取得重複失敗

### ISSUE THREAD

**Issue by ACGN2006** [hgalytoby/MyselfAnimeDownloader#34]
影片取得重複失敗的問題，是否為myself主動偵測可疑IP

**Comment by hgalytoby** [comment]
> 影片取得重複失敗的問題，是否為myself主動偵測可疑IP

我剛剛用 1.1.10 版下載一部影片是沒問題的，但是我不知道下載大量會不會有什麼問題。

需要您提供更詳細的情況。

如果要驗證是否是 IP 問題，你可以換 IP 嘗試下載看看，如果可以下載有可能是 IP 問題了。

**Comment by ShionMegumi** [comment]
這邊嘗試過換IP下載，依然有無法取得影片資料的問題。
但也並非全部不能，有些是能完整下載/缺少1-2集，但有些是全套也無法下載，可是Myself網站那邊是可以觀看的。
我猜Myself網有可能最近有修復過？上周有一些無法播放的片源現在也能看到了。

**Comment by hgalytoby** [comment]
> 這邊嘗試過換IP下載，依然有無法取得影片資料的問題。 但也並非全部不能，有些是能完整下載/缺少1-2集，但有些是全套也無法下載，可是Myself網站那邊是可以觀看的。 我猜Myself網有可能最近有修復過？上周有一些無法播放的片源現在也能看到了。

可以提供動畫名稱嗎？

我下載試試看。

**Comment by ShionMegumi** [comment]
> > 這邊嘗試過換IP下載，依然有無法取得影片資料的問題。 但也並非全部不能，有些是能完整下載/缺少1-2集，但有些是全套也無法下載，可是Myself網站那邊是可以觀看的。 我猜Myself網有可能最近有修復過？上周有一些無法播放的片源現在也能看到了。
> 
> 可以提供動畫名稱嗎？
> 
> 我下載試試看。

我剛剛也再試了一下，發現之前曾經成功下載過的現在也同樣沒辦法了。
我到昨晚為止都能使用，不過關掉過一次後就沒辦法再載了。也不太清楚會不會是我電腦的問題，這邊已經嘗試重開電腦、重載軟件等等的方法，依然沒辦法下。

我測試的：
命運石之門, 殺戮的天使, 反叛的魯路修（以前網站沒辦法播放）
Fate UBW, 86, 排球少年（以前能成功下載和網站播放但現在失敗）

**Comment by hgalytoby** [comment]
> > > 這邊嘗試過換IP下載，依然有無法取得影片資料的問題。 但也並非全部不能，有些是能完整下載/缺少1-2集，但有些是全套也無法下載，可是Myself網站那邊是可以觀看的。 我猜Myself網有可能最近有修復過？上周有一些無法播放的片源現在也能看到了。
> > 
> > 
> > 可以提供動畫名稱嗎？
> > 我下載試試看。
> 
> 我剛剛也再試了一下，發現之前曾經成功下載過的現在也同樣沒辦法了。 我到昨晚為止都能使用，不過關掉過一次後就沒辦法再載了。也不太清楚會不會是我電腦的問題，這邊已經嘗試重開電腦、重載軟件等等的方法，依然沒辦法下。
> 
> 我測試的： 命運石之門, 殺戮的天使, 反叛的魯路修（以前網站沒辦法播放） Fate UBW, 86, 排球少年（以前能成功下載和網站播放但現在失敗）

我剛剛測試了，確實網站上可以看但是不能下載，我回家再研究。

**Comment by hgalytoby** [comment]
@ACGN2006 @ShionMegumi https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.11

**Comment by ShionMegumi** [comment]
> @ACGN2006 @ShionMegumi
> 
> 花了好幾個小時才研究好。
> 
> 我測試過了可以下載，你們可以試試看。
> 
> 1.1.11版本
> 
> https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.11

現在可以下載一部分了，以前成功過的都能下，不過有些一直顯示著【下載中】，但我放著跑了一小時多進度條還是保持0%

**Comment by thomson1973** [comment]
> > @ACGN2006 @ShionMegumi
> > 花了好幾個小時才研究好。
> > 我測試過了可以下載，你們可以試試看。
> > 1.1.11版本
> > https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.11
> 
> 現在可以下載一部分了，以前成功過的都能下，不過有些一直顯示著【下載中】，但我放著跑了一小時多進度條還是保持0%
> 

我也是相同的狀況，可以確定的是不起眼女主角兩季都會停在 0% 下載中

**Comment by hgalytoby** [comment]
> 現在可以下載一部分了，以前成功過的都能下，不過有些一直顯示著【下載中】，但我放著跑了一小時多進度條還是保持0%
> 

提供下載的影片，我下班測試。


> 另外不知道是不是我的錯覺，感覺下載速度比以前緩慢了。

簡單解釋一下

以前拿片源的時候會有好幾個入口可以拿，這些入口是有權重的。

權重越高的入口拿影片速度越快。

我昨天在測試的時候有看到一直拿片源失敗，我覺得是官方給的片源路口都是權重低的，才會變慢。

所以這不是你的錯覺。

**Comment by hgalytoby** [comment]
> > > @ACGN2006 @ShionMegumi
> > > 花了好幾個小時才研究好。
> > > 我測試過了可以下載，你們可以試試看。
> > > 1.1.11版本
> > > https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.11
> > 
> > 
> > 現在可以下載一部分了，以前成功過的都能下，不過有些一直顯示著【下載中】，但我放著跑了一小時多進度條還是保持0%
> 
> 我也是相同的狀況，可以確定的是不起眼女主角兩季都會停在 0% 下載中

我下班在測試看看。

**Comment by hingithub** [comment]
昨晚下載的時候也有發現下載完成的檔案打開只有不到3分鐘，但在網站看實際片長有24分鐘。

其中一個檔案如下：
戰勇Senyuu第 01 話

已給星星，十分感謝!

**Comment by hgalytoby** [comment]
> 昨晚下載的時候也有發現下載完成的檔案打開只有不到3分鐘，但在網站看實際片長有24分鐘。
> 
> 其中一個檔案如下： 戰勇Senyuu第 01 話
> 
> 已給星星，十分感謝!

好，回家測試看看。

**Comment by ShionMegumi** [comment]
> 昨晚下載的時候也有發現下載完成的檔案打開只有不到3分鐘，但在網站看實際片長有24分鐘。

殺戮的天使也是同樣，但檔案都只有10分鐘

**Comment by hgalytoby** [comment]
> > 昨晚下載的時候也有發現下載完成的檔案打開只有不到3分鐘，但在網站看實際片長有24分鐘。
> 
> 殺戮的天使也是同樣狀況，檔案只有10分鐘

好，下班測試看看。

**Comment by hgalytoby** [comment]
@thomson1973 我修好了也測試過下載不起眼第一季 02 ~ 06 第二季 01。

@ShionMegumi 我修好了也測試過下載殺戮的天使 01 ~ 03。

@hingithub 我修好了也測試過下載戰勇Senyuu第 01 話，但是官方影片只有6分半，不知道你為什麼有24分鐘。

**Comment by thomson1973** [comment]
> @thomson1973 我修好了也測試過下載不起眼第一季 02 ~ 06 第二季 01。
v1.1.12 已修復問題，大感謝。

**Comment by dark890710** [comment]
> @thomson1973 我修好了也測試過下載不起眼第一季 02 ~ 06 第二季 01。
> 
> @ShionMegumi 我修好了也測試過下載殺戮的天使 01 ~ 03。
> 
> @hingithub 我修好了也測試過下載戰勇Senyuu第 01 話，但是官方影片只有6分半，不知道你為什麼有24分鐘。
> 
> https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.12
> 
> 官方如果持續改拿影片的方式，我就得持續更新程式。
> 
> 還有下載速度變慢我也沒辦法，可以嘗試重新開啟程式或許會變快，因為可能會拿到權重高的片源。
> 
> 畢竟這是我兩年前寫的程式了，我不打算大改拿影片的邏輯過程，因為我還有別的事情要忙。

不知道是不是又改方式了，上面說的幾部我下載都一直讀取失敗

**Comment by dark890710** [comment]
> > 不知道是不是又改方式了，上面說的幾部我下載都一直讀取失敗
> 
> 我在下載一次是沒有問題的。
> 
> ![image](https://user-images.githubusercontent.com/50397689/202761362-86044ef3-25c3-4659-ba9e-e29bc3032aec.png)
> 
> 你是用 1.1.12 版本嗎?

我把資料夾刪掉重新下載就可以了，感謝大大!

**Comment by kevinnlnlouo** [comment]
> > 不知道是不是又改方式了，上面說的幾部分我下載都一直讀取失敗
> 
> 我在下載一次是沒有問題的。
> 
> ![圖片](https://user-images.githubusercontent.com/50397689/202761362-86044ef3-25c3-4659-ba9e-e29bc3032aec.png)
> 
> 你是用 1.1.12 版本嗎？

請問現在1.1.12不能下載

**Comment by hgalytoby** [comment]
請問現在1.1.12不能下載

我不太懂，你可以詳細敘述一下你想表達的意思嗎？

我剛用 Ｍac 是可以下載的。

![image](https://user-images.githubusercontent.com/50397689/202967030-87c33eff-0245-4f98-9c73-f38a21c4a8a3.png)

**Comment by hgalytoby** [comment]
> 請問現在1.1.12不能下載

我不太懂，你可以詳細敘述一下你想表達的意思嗎？

我剛用 Ｍac 是可以下載的。

![image](https://user-images.githubusercontent.com/50397689/202967030-87c33eff-0245-4f98-9c73-f38a21c4a8a3.png)

**Comment by kevinnlnlouo** [comment]
我是用Windows 出現 重複失敗

**Comment by hgalytoby** [comment]
> 我是用Windows 出現 重複失敗

目前手邊沒 windows 電腦，回家才能測試。

但我覺得我 Mac 可以 Windows 就應該可以。

你能不能附上一點圖呢？你是台灣 IP 嗎？還是海外的？

因為有時候有 IP 問題會拿不到資料。

**Comment by kevinnlnlouo** [comment]
> > 我是用Windows 出現 重複失敗
> 
> 目前手邊沒 windows 電腦，回家才能測試。
> 
> 但我覺得我 Mac 可以 Windows 就應該可以。
> 
> 你能不能附上一點圖呢？你是台灣 IP 嗎？還是海外的？
> 
> 因為有時候有 IP 問題會拿不到資料。

![image](https://user-images.githubusercontent.com/118708431/202969874-fa9129d6-4ee1-47a7-9039-40c60bfca2c7.png)
IP是台灣 防火牆也關了

**Comment by hgalytoby** [comment]
> ![image](https://user-images.githubusercontent.com/118708431/202969874-fa9129d6-4ee1-47a7-9039-40c60bfca2c7.png) IP是台灣 防火牆也關了 也重新下載過


這是我 windows 的圖，確定是可以下載的。

![image](https://user-images.githubusercontent.com/50397689/203052705-cea79127-6a98-4443-9eae-79e814028e75.png)

你可以嘗試重新下載下載器或者關閉防毒，以前有一次是防毒在擋。

如果都不行你可以嘗試用手機網路下載看看，不知道會不會是你的網路有擋。

**Comment by hgalytoby** [comment]
@thomson1973 @ACGN2006 @ShionMegumi @hingithub @dark890710 @kevinnlnlouo 

如果還有在使用下載器，可以使用1.1.13版，https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.13

我修復了下載極慢的原因了。

**Comment by hitori2022** [comment]
您好 ，我下載了登山少女第二季，其他集數都正常下載完成只有第9集卡在97%，也有把下載器刪掉再使用幾次還是一樣。![螢幕擷取畫面_20221123_050547](https://user-images.githubusercontent.com/118886934/203507783-122ff61b-2a0e-49a7-bb51-0e9c36ca7f52.png)

**Comment by hgalytoby** [comment]
> 您好 ，我下載了登山少女第二季，其他集數都正常下載完成只有第9集卡在97%，也有把下載器刪掉再使用幾次還是一樣。![螢幕擷取畫面_20221123_050547](https://user-images.githubusercontent.com/118886934/203507783-122ff61b-2a0e-49a7-bb51-0e9c36ca7f52.png)

我下班在測試看看。

**Comment by ACGN2006** [comment]
> 您好 ，我下載了登山少女第二季，其他集數都正常下載完成只有第9集卡在97%，也有把下載器刪掉再使用幾次還是一樣。![螢幕擷取畫面_20221123_050547](https://user-images.githubusercontent.com/118886934/203507783-122ff61b-2a0e-49a7-bb51-0e9c36ca7f52.png)
> 
> 

可以到官網查看有沒有影片播放問題哦，像「妹控哥哥與雙胞胎妹妹」第三集11秒左右本身就有問題，是沒有辦法播放的

**Comment by hitori2022** [comment]
> > 您好 ，我下載了登山少女第二季，其他集數都正常下載完成只有第9集卡在97%，也有把下載器刪掉再使用幾次還是一樣。![螢幕擷取畫面_20221123_050547](https://user-images.githubusercontent.com/118886934/203507783-122ff61b-2a0e-49a7-bb51-0e9c36ca7f52.png)
> 
> 可以到官網查看有沒有影片播放問題哦，像「妹控哥哥與雙胞胎妹妹」第三集11秒左右本身就有問題，是沒有辦法播放的

了解，看來是影片的問題，卡在13:04。謝謝~已按星星。

**Comment by hgalytoby** [comment]
看來是官方的問題，答案已解。

**Comment by hgalytoby** [comment]
如果還有新的問題請在開新的 Issues，這裡先關閉了。
