### ISSUE TITLE
MyselfAnimeDownloader 取得資料失敗

### ISSUE THREAD

**Issue by j30915gary** [hgalytoby/MyselfAnimeDownloader#37]
首先真的很開心能夠繼續營運!!!

通常都是等一季一次收作品，但這次遇到問題如下

目前有的影片可下載有的會出現這個，"取得影片資料中(失敗XXX次)"

例如：菜鳥鍊金術師開店營業中 第1話 到 第12話 都出現此無法下載狀況
　　　忍之一時 第1話 到 第4話 正常，但 第5話 開始無法下載(跟上述一樣)

已經是使用了 Ver.1.1.13版 還是一樣，此狀況目前大多數都作品都無法下載

請問這該如何解決?

**Comment by j30915gary** [comment]
> 首先真的很開心能夠繼續營運!!!
> 
> 通常都是等一季一次收作品，但這次遇到問題如下
> 
> 目前有的影片可下載有的會出現這個，"取得影片資料中(失敗XXX次)"
> 
> 例如：菜鳥鍊金術師開店營業中 第1話 到 第12話 都出現此無法下載狀況
> 　　　忍之一時 第1話 到 第4話 正常，但 第5話 開始又無法下載(跟上述一樣)
> 
> 已經是使用了 Ver.1.1.13版 還是一樣
> 
> 請問這該如何解決?

**Comment by hgalytoby** [comment]
> 首先真的很開心能夠繼續營運!!!
> 
> 通常都是等一季一次收作品，但這次遇到問題如下
> 
> 目前有的影片可下載有的會出現這個，"取得影片資料中(失敗XXX次)"
> 
> 例如：菜鳥鍊金術師開店營業中 第1話 到 第12話 都出現此無法下載狀況 　　　忍之一時 第1話 到 第4話 正常，但 第5話 開始無法下載(跟上述一樣)
> 
> 已經是使用了 Ver.1.1.13版 還是一樣，此狀況目前大多數都作品都無法下載
> 
> 請問這該如何解決?

研究了一下，官方現在新的影片好像是用新的方式拿影片，所以只要是新的影片現在的下載器都無法下載是正常的。

我現在修好了，晚點上傳後我會 tag 你。

**Comment by hgalytoby** [comment]
@j30915gary  https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.14

**Comment by j30915gary** [comment]
@hgalytoby 太感謝了!!

若使用有其他問題會馬上回報，也祝繼續營運順利!
