### ISSUE TITLE
MyselfAnimeDownloader 取得資料失敗 新更新的都會失敗

### ISSUE THREAD

**Issue by tyantgx** [hgalytoby/MyselfAnimeDownloader#38]

**Comment by hgalytoby** [comment]
我修好了 1.1.14 版本

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.14

**Comment by tyantgx** [comment]
THX 大大

**Comment by methosjim** [comment]
網站復活實在太開心了
看到大大更新下載器就更開心了
但我這邊卻無法正常運作QQ

![image](https://user-images.githubusercontent.com/44969379/209488814-6c63426f-599e-4791-b92f-1d8820eac677.png)
最新版，但完全不會動

![image](https://user-images.githubusercontent.com/44969379/209488874-f674df2d-595f-4de2-ba8f-aec4c0e11fee.png)
關閉重開後會變成取得失敗

小弟我對程式不熟，載最新版有什麼要事前設定還是什麼之類的嗎?
網站關閉前的版本使用上很正常，求救，感恩!

**Comment by hgalytoby** [comment]
> 網站復活實在太開心了 看到大大更新下載器就更開心了 但我這邊卻無法正常運作QQ
> 
> ![image](https://user-images.githubusercontent.com/44969379/209488814-6c63426f-599e-4791-b92f-1d8820eac677.png) 最新版，但完全不會動
> 
> ![image](https://user-images.githubusercontent.com/44969379/209488874-f674df2d-595f-4de2-ba8f-aec4c0e11fee.png) 關閉重開後會變成取得失敗
> 
> 小弟我對程式不熟，載最新版有什麼要事前設定還是什麼之類的嗎? 網站關閉前的版本使用上很正常，求救，感恩!

我這邊測試下載孤獨搖滾是沒有問題的。

如果你是下載不行但可以線上看，不知道會不會是防毒問題。

https://github.com/hgalytoby/MyselfAnimeDownloader/issues/14

**Comment by hgalytoby** [comment]
如還有後續問題，請再開 issues。
