### ISSUE TITLE
打包版正常執行，但使用源碼執行時無法下載

### ISSUE THREAD

**Issue by s881116s** [hgalytoby/MyselfAnimeDownloader#39]
如標題，使用源碼執行下載時，cmd會出現「websocket 短時間連線太多會出問題」的錯誤；但拿打包的程式下載時就沒有出錯。
我大咯看了一眼源碼，感覺問題應該是出在 ws_get_host_and_m3u8_url 函式。但以我的三腳貓功夫沒辦法自行debug，再麻煩大大看一下。

另外share資料夾的myself方法似乎還是舊版的，如果大大不介意的話，希望可以更新一下，謝謝。

**Comment by hgalytoby** [comment]
> 如標題，使用源碼執行下載時，cmd會出現「websocket 短時間連線太多會出問題」的錯誤；但拿打包的程式下載時就沒有出錯。 我大咯看了一眼源碼，感覺問題應該是出在 ws_get_host_and_m3u8_url 函式。但以我的三腳貓功夫沒辦法自行debug，再麻煩大大看一下。
> 

我也不知道怎麼解決你的問題，你可以在這邊

https://github.com/hgalytoby/MyselfAnimeDownloader/blob/master/myself_thread.py#L320

印出錯誤訊息看一下是錯了什麼，或者貼給我看看。


> 另外share資料夾的myself方法似乎還是舊版的，如果大大不介意的話，希望可以更新一下，謝謝。

下班回家有空就更新。

**Comment by s881116s** [comment]
沒事了，我找到問題在哪裡了，不是原始碼的問題。
當初安裝pip套件時不知道為什麼沒有安裝到websocket-client，補安裝時卻安裝到websocket才出錯，補安裝正確的套件後就正常了。

**Comment by hgalytoby** [comment]
> 沒事了，我找到問題在哪裡了，不是原始碼的問題。 當初安裝pip套件時不知道為什麼沒有安裝到websocket-client，補安裝時卻安裝到websocket才出錯，補安裝正確的套件後就正常了。

我有改套件。

https://github.com/hgalytoby/MyselfAnimeDownloader/blob/master/UpdateLog.md#ver1111-20221117
