### ISSUE TITLE
部分正確網址無法偵測

### ISSUE THREAD

**Issue by aerosoul** [hgalytoby/MyselfAnimeDownloader#4]
1.若以www開頭的網址無法偵測。例如從https://www.myself... 包含"www."的首頁進入後再點選的個別連結都會有www開頭，連結其實有效但是程式無法正確偵測。
2.特殊分類的區域多半無法偵測到內容，不隸屬於"完結"或"連載"分類的連結都無法偵測。例如"地味變"雖是連載中但被分屬於R18+分類，特殊分類的連結都無法偵測。

**Comment by hgalytoby** [comment]
> 1.若以www開頭的網址無法偵測。例如從[https：//www.myself](https://www.myself) ...包含“ www。”的首頁進入後再點選的個別連結都會有www開頭，連結實際上有效但是程式無法正確發現。2.特殊
> 分類的區域多半無法檢測到內容，不隸屬屬於“完結”或“連載”分類的連結都無法檢測。例如“地味變”雖是連載中但被分屬於R18 +分類，特殊分類的連結都無法偵測。


1.我知道了，我沒考慮到 www 的情況！

2.這個問題應該是全 R18 吧？官網規定要登入後才能觀看，因為我的程式並沒有登入的功能，不能查看是正常的！

這周我會新增登入功能 與 解決網址 `www`的問題。

謝謝您發現的問題~

**Comment by hgalytoby** [comment]
> 1.若以www開頭的網址無法偵測。例如從https://www.myself... 包含"www."的首頁進入後再點選的個別連結都會有www開頭，連結其實有效但是程式無法正確偵測。
> 2.特殊分類的區域多半無法偵測到內容，不隸屬於"完結"或"連載"分類的連結都無法偵測。例如"地味變"雖是連載中但被分屬於R18+分類，特殊分類的連結都無法偵測。

Ok!

修正好  www 的問題與新增了登入功能現在可以看到R18了。

如有發現 Bug 請再通知!

謝謝您!

**Comment by aerosoul** [comment]
謝謝您的更新! 想請教一個其他的問題，把MyselfAnime.exe拿到VirusTotal去掃描的話，會有3個engine認為是木馬或惡意程式。當然你都已經公開原始碼，我相信這都是誤判。只是好奇如果自己寫的程式被誤判，通常有沒有解決辦法? 不過在下對python不熟。

**Comment by hgalytoby** [comment]
這我不知道耶.

不然你貼一下他掃到的病毒圖給我看.

我去 Google 看看!

**Comment by hgalytoby** [comment]
這是 Windows 內建的防毒.

https://user-images.githubusercontent.com/50397689/107117125-04915480-68b3-11eb-9597-41ca413aa6b1.mp4

**Comment by hgalytoby** [comment]
> 謝謝您的更新! 想請教一個其他的問題，把MyselfAnime.exe拿到VirusTotal去掃描的話，會有3個engine認為是木馬或惡意程式。當然你都已經公開原始碼，我相信這都是誤判。只是好奇如果自己寫的程式被誤判，通常有沒有解決辦法? 不過在下對python不熟。

我剛剛測試 Google 了一下

這是我用網頁測的結果

https://www.virustotal.com/gui/file/a621f6069d289efbe4b73a8769578dd9eee96cd8f3312ee59a8892eef18c30d1/detection

誤判的原因是因為打包成應用程式的套件的問題。

這是我查到的問題解決方法

https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg/52054580#52054580

**Comment by hgalytoby** [comment]
如果還有問題請在發出提問!

這邊將關閉問題。

如果覺得此專案不錯，請幫我按星星!

謝謝您~
