### ISSUE TITLE
下載時會出現取得影片資料失敗

### ISSUE THREAD

**Issue by victoria0131** [hgalytoby/MyselfAnimeDownloader#40]
作業系統:windows 10
有開高速了

![螢幕擷取畫面 2023-04-17 203720](https://user-images.githubusercontent.com/130993143/232487834-4cca664a-89e4-4e81-b642-12045158547d.png)

**Comment by hgalytoby** [comment]
> 作業系統:windows 10 有高速了
> 
> ![螢幕摘取畫面 2023-04-17 203720](https://user-images.githubusercontent.com/130993143/232487834-4cca664a-89e4-4e81-b642-12045158547d.png)

我這邊測試下載沒有問題。

你看看是不是防毒擋掉了 https://github.com/hgalytoby/MyselfAnimeDownloader/issues/14

**Comment by victoria0131** [comment]
出現這個但還是一樣失敗
![螢幕擷取畫面 2023-04-18 181354](https://user-images.githubusercontent.com/130993143/232753172-b826d8bc-69a6-4c81-a189-39430b5aaa7f.png)
![螢幕擷取畫面 2023-04-18 184049](https://user-images.githubusercontent.com/130993143/232753180-454a45ed-9c08-4c87-98a4-e0b548960d7f.png)

**Comment by victoria0131** [comment]
對
確認過沒有安裝其他防毒軟體了

**Comment by hgalytoby** [comment]
> 對 確認過沒有安裝其他防毒軟體了

你如果網頁上看動漫沒問題，但是下載器有問題的話，那有兩個選擇。

第一是我開弄一個測試的下載器給你用，然後你將下載失敗的日誌傳給我，我來看問題點在哪。

第二是你跟我用 dc 聊，我看你畫面直接 debug。

**Comment by victoria0131** [comment]
那用dc
vic#7713

**Comment by hgalytoby** [comment]
> 那用dc

我加你了，你可以把你的訊息刪除。

**Comment by AliceFongs** [comment]
> 作業系統:windows 10 有開高速了
> 
> ![螢幕擷取畫面 2023-04-17 203720](https://user-images.githubusercontent.com/130993143/232487834-4cca664a-89e4-4e81-b642-12045158547d.png)

我也發生一樣的問題
Win7、8都一樣
(防毒全關了)

**Comment by AliceFongs** [comment]
> 這串樓主是因為SSL原因導致下載不了，你也試試看這個版本。 https://drive.google.com/file/d/1S7Q64FaBPZJuDz4mZo8eesrkHa_wfQoo/view?usp=sharing
> 
> 打開程序後會多個小黑窗，如果不能再下載請您將小黑窗圖片給我，如果可以下載請回复給我，因為我這裡沒有下載不了的問題。
> 
> 打開以後會是這個樣子 ![圖像](https://camo.githubusercontent.com/e937ac07aa07c87337d88c179fbab87a89ba660b7f72d97c3283c575e28cb48c/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f313039383534353636333434363336383237372f313130303035363235373038393532333732322f696d6167652e706e673f77696474683d373035266865696768743d323832)

![image](https://user-images.githubusercontent.com/121262128/234861800-2c79c01f-3bba-4c84-9c9c-7eccf8478620.png)
看來也是SSL有問題
不過可以正常載了

但另外還有一個問題
只要開過一次程式產生了"config.json"
程式關掉之後就再也打不開了
只能把"config.json"刪掉才能再開

**Comment by hgalytoby** [comment]
> > 這串樓主是因為SSL原因導致下載不了，你也試試看這個版本。 https://drive.google.com/file/d/1S7Q64FaBPZJuDz4mZo8eesrkHa_wfQoo/view?usp=sharing
> > 打開程序後會多個小黑窗，如果不能再下載請您將小黑窗圖片給我，如果可以下載請回复給我，因為我這裡沒有下載不了的問題。
> > 打開以後會是這個樣子 ![圖像](https://camo.githubusercontent.com/e937ac07aa07c87337d88c179fbab87a89ba660b7f72d97c3283c575e28cb48c/68747470733a2f2f6d656469612e646973636f72646170702e6e65742f6174746163686d656e74732f313039383534353636333434363336383237372f313130303035363235373038393532333732322f696d6167652e706e673f77696474683d373035266865696768743d323832)
> 
> ![image](https://user-images.githubusercontent.com/121262128/234861800-2c79c01f-3bba-4c84-9c9c-7eccf8478620.png) 看來也是SSL有問題 不過可以正常載了
> 
> 但另外還有一個問題 只要開過一次程式產生了"config.json" 程式關掉之後就再也打不開了 只能把"config.json"刪掉才能再開


因為我給你的這版是有解決 ssl 的問題。

我這裡沒有打開後就再也打不開的問題。

`config.json`是我放設定的檔案，你把 `config.json` 貼上來給我看。

你再次打開的時候小黑窗有出來嗎?

**Comment by AliceFongs** [comment]
> 因為我給你的這個版本是解決 ssl 的問題。
> 
> 我這裡沒有打開後就再打不開的問題。
> 
> `config.json`是我放設定的檔案，你把`config.json`貼上來給我看。
> 
> 你下次打開的時候小黑窗有出來嗎？

```
{
  "path": "D:\\\路徑",
  "speed": {
    "type": "slow",
    "value": 1
  },
  "simultaneous": 5,
  "status_bar": true,
  "update": true
}
```
這是第一次打開出現的內容
也就是刪掉之後又出現的

就是只有cmd出來 主程式沒反應
有時候會跳出一個小的錯誤框
但大部分都是沒反應比較多

**Comment by AliceFongs** [comment]
> 因為我給你的這版是有解決 ssl 的問題。
> 
> 我這裡沒有打開後就再也打不開的問題。
> 
> `config.json`是我放設定的檔案，你把 `config.json` 貼上來給我看。
> 
> 你再次打開的時候小黑窗有出來嗎?

```
{
  "path": "D:\\\路徑",
  "speed": {
    "type": "slow",
    "value": 1
  },
  "simultaneous": 5,
  "status_bar": true,
  "update": true
}
```
這是第一次開出現的 `config.json`
也就是刪掉之後自己產生的內容(沒有改設定)

就是只有cmd有出來 主程式沒反應
有時候還會跑出一個錯誤的小框
但基本上都是沒反應比較多

這個問題從V1.1.13就開始了
本來想說更新會修復 但還是一樣
感覺似乎是從網站大改之後開始的
以前用V1.1.13的時候不會這樣

**Comment by hgalytoby** [comment]
> > 因為我給你的這版是有解決 ssl 的問題。
> > 我這裡沒有打開後就再也打不開的問題。
> > `config.json`是我放設定的檔案，你把 `config.json` 貼上來給我看。
> > 你再次打開的時候小黑窗有出來嗎?
> 
> ```
> {
>   "path": "D:\\\路徑",
>   "speed": {
>     "type": "slow",
>     "value": 1
>   },
>   "simultaneous": 5,
>   "status_bar": true,
>   "update": true
> }
> ```
> 
> 這是第一次開出現的 `config.json` 也就是刪掉之後自己產生的內容(沒有改設定)
> 
> 就是只有cmd有出來 主程式沒反應 有時候還會跑出一個錯誤的小框 但大部分都是沒反應比較多
> 
> 這個問題從V1.1.13就開始了 本來想說更新會修復 但還是一樣 感覺似乎是從網站大改之後開始的 以前用V1.1.13的時候不會這樣

所以你的意思是你拿原本的 release 版本與我上面給的 cmd 版本都有重開後打不開的問題是嗎？

**Comment by AliceFongs** [comment]
> 所以你的意思是你拿原本的 release 版本與我上面給的 cmd 版本都有重開後打不開的問題是嗎？

對 當時是V1.1.13
想說怎麼打不開
可能需要更新 就改V1.1.14
但結果還是一樣
後來刪掉重解壓又正常
最後查一查才發現
是`config.json`有問題
我大概一年多沒用過了
所以推測會不會跟網站大改有關係

**Comment by hgalytoby** [comment]
> 對 當時是V1.1.13 想說怎麼打不開 可能需要更新 就改V1.1.14 但結果還是一樣 後來刪掉重解壓又正常 最後查一查才發現 是`config.json`有問題 我大概一年多沒用過了 所以推測會不會跟網站大改有關係

我認為應該不是 `config.json` 的問題。

如果你重新下載新的，接著打開後什麼動作都不做就關閉程式，在打開程式就變成打不開的話，就要執行原始碼查看問題了。

如果你是用新的程式打開後有做跟設定相關的動作或者是下載動漫類似的動作，或許能從這方面查查看問題。

**Comment by AliceFongs** [comment]
> 你重新下載新的，接著打開後什麼動作都不做就關閉程式，再打開程式就變成打不開

不管是這個

> 如果你是用新的程式打開後有做跟設定相關的動作或者是下載動漫類似的動作

還是這個

都會造成打不開的問題
只有在我把`config.json`刪掉才能解決
這問題發生在Win7、8、V1.1.13、V1.1.14

>就要執行原始碼查看問題了

這個要怎麼查

**Comment by hgalytoby** [comment]
> 都會造成打不開的問題 只有在我把`config.json`刪掉才能解決 這問題發生在Win7、8、V1.1.13、V1.1.14
> 
windows 10 不會嗎?

> 這個要怎麼查
就是用原始碼直接跑程式而不是 exe 看錯誤在哪裡而已。

**Comment by AliceFongs** [comment]
> windows 10 不會嗎?

我沒有Win10

> 就是用原始碼直接跑程式而不是 exe 看錯誤在哪裡而已。

這個我就不會了XD

**Comment by hgalytoby** [comment]
> > windows 10 不會嗎?
> 
> 我沒有Win10
> 
> > 就是用原始碼直接跑程式而不是 exe 看錯誤在哪裡而已。
> 
> 這個我就不會了XD

1.discord 分享畫面我看你螢幕幫你 debug，需要裝程式語言。
2.每次你刪掉 config.json。

**Comment by AliceFongs** [comment]
> 1.discord 分享畫面我看你螢幕幫你 debug，需要裝程式語言。
> 
> 2.就按照你說的刪掉 `config.json` 解決問題，因為我這裡無法呈現你的問題。

那我就用bat檔讓他開機自動刪吧
DC分享會卡 不太行

**Comment by AliceFongs** [comment]
能做一個隱藏cmd的版本嗎
多一個窗在那 有點礙眼XD

**Comment by hgalytoby** [comment]
> 能做一個隱藏cmd的版本嗎 多一個窗在那 有點礙眼XD

我回家整個程式更新  release。

**Comment by AliceFongs** [comment]
> 我回家整個程式更新 release。

好 感謝

**Comment by hgalytoby** [comment]
> > 我回家整個程式更新 release。
> 
> 好 感謝

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.15

**Comment by AliceFongs** [comment]
> https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.15

使用正常
