### ISSUE TITLE
1.1.15版更新提示

### ISSUE THREAD

**Issue by zelda0079** [hgalytoby/MyselfAnimeDownloader#42]
我去https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.15
下載檔案(WINDOWS版本和WINDOWS DEBUG版本)，檔案顯示是1.1.14版，彈出作者更新了!的視窗

**Comment by hgalytoby** [comment]
> 我去https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.15 下載檔案(WINDOWS版本和WINDOWS DEBUG版本)，檔案顯示是1.1.14版，彈出作者更新了!的視窗

好，我已經替換完新的 Debug 版本了。

**Comment by zelda0079** [comment]
> > 我去https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.15 下載檔案(WINDOWS版本和WINDOWS DEBUG版本)，檔案顯示是1.1.14版，彈出作者更新了!的視窗
> 
> 好，我已經替換完新的 Debug 版本了。

WINDOWS版本也是舊版

**Comment by hgalytoby** [comment]
> > > 我去https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/Ver1.1.15 下載檔案(WINDOWS版本和WINDOWS DEBUG版本)，檔案顯示是1.1.14版，彈出作者更新了!的視窗
> > 
> > 
> > 好，我已經替換完新的 Debug 版本了。
> 
> WINDOWS版本也是舊版

好，我已經替換完新的版本了。

**Comment by zelda0079** [comment]
謝謝!
