### ISSUE TITLE
突然跳掉後一直打不開

### ISSUE THREAD

**Issue by 87abao** [hgalytoby/MyselfAnimeDownloader#46]
前幾日下載中，將視窗最小化，之後因在電腦桌前睡著電腦自動進入休眠，然而喚醒後發現程式已自動被關閉，也無法進入，顯示如附圖的視窗，雖然以前也常在下載途中將電腦休眠，但只有這次出現異常。

喚醒電腦後畫面與關閉前並無不同，依舊停留在原先的畫面，唯一只有下載器被關閉，並發生以上情況。

嘗試過重新解壓縮，甚至全部刪除後到github重新下載，也試過window_debug版，但是依然顯示相同情況。
已爬過#9、#22和#25的文，感覺狀況有點不一樣，奈何本人對程式語言一竅不通，可能有所誤判，因此開了新的issue，麻煩大大幫忙解惑了，謝謝!!

![擷取](https://github.com/user-attachments/assets/1955cb37-436f-4350-b06a-271a7f38832e)

**Comment by hgalytoby** [comment]
程式資料夾下有個 Log 資料夾，把這個資料夾刪掉就可以了。

**Comment by 87abao** [comment]
已經照你所說的刪除DownloadQueue.json了，現在已可以重新進入，真的非常感謝你的幫忙!

**Comment by hgalytoby** [comment]
> 已經照你所說的刪除DownloadQueue.json了，現在已可以重新進入，真的非常感謝你的幫忙!

不客氣。
