### ISSUE TITLE
時常出現下兩則訊息 不知道是不是正常現象

### ISSUE THREAD

**Issue by Hungnoob** [hgalytoby/MyselfAnimeDownloader#5]
HTTPSConnectionPool(host='vpx16.myself-bbs.com', port=443): Read timed out. (read timeout=3) https://vpx01.myself-bbs.com/44367/002/720p_096.ts

基礎錯誤 ("Connection broken: ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None)", ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None))

**Comment by hgalytoby** [comment]
程式有崩潰嗎?

**Comment by hgalytoby** [comment]
> HTTPSConnectionPool(host='vpx16.myself-bbs.com', port=443): Read timed out. (read timeout=3) https://vpx01.myself-bbs.com/44367/002/720p_096.ts
> 
> 基礎錯誤 ("Connection broken: ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None)", ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None))

程式有崩潰嗎?

**Comment by hgalytoby** [comment]
> HTTPSConnectionPool(host='vpx16.myself-bbs.com', port=443): Read timed out. (read timeout=3) https://vpx01.myself-bbs.com/44367/002/720p_096.ts
> 
> 基礎錯誤 ("Connection broken: ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None)", ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None))

這個原因是因為  沒意外是因為連接值設的高。

對方伺服器沒辦法短時間回應你的需求。

所以會出現這個錯誤。

但我有 try: except: 切換分流。

**Comment by hgalytoby** [comment]
> HTTPSConnectionPool(host='vpx16.myself-bbs.com', port=443): Read timed out. (read timeout=3) https://vpx01.myself-bbs.com/44367/002/720p_096.ts
> 
> 基礎錯誤 ("Connection broken: ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None)", ConnectionResetError(10054, '遠端主機已強制關閉一個現存的連線。', None, 10054, None))

你就想像

你一次下載12個影片

連接值是16

所以12*16

你一瞬間跟伺服器訪問192次

或許你覺得沒什麼

但如果更多人同時間跟你一樣一起訪問

這就會造成伺服器負擔了!

**Comment by Hungnoob** [comment]
> 程式有崩潰嗎?

下載進度會不動許久，到沒崩潰過
我是一次下載一個就是了，但聽你這麼說，應該是整體狀況的關係，跟我的設定無關。
謝謝你的回覆。

**Comment by Hungnoob** [comment]
> > 程式有崩潰嗎?
> 
> 下載進度會不動許久，到沒崩潰過
> 我是一次下載一個就是了，但聽你這麼說，應該是整體狀況的關係，跟我的設定無關。
> 謝謝你的回覆。

像我現在是read time out 兩次後 就不動二十分鐘了

**Comment by hgalytoby** [comment]
> > 程式有崩潰嗎?
> 
> 下載進度會不動許久，到沒崩潰過
> 我是一次下載一個就是了，但聽你這麼說，應該是整體狀況的關係，跟我的設定無關。
> 謝謝你的回覆。

你每個影片都是這樣嗎?

**Comment by Hungnoob** [comment]
我只載過化物語第一集，也有卡過，不過重開就會好一下子了。

**Comment by hgalytoby** [comment]
> 我只載過化物語第一集，也有卡過，不過重開就會好一下子了。

好的我知道了

我這邊也有發生這樣的事情

我猜測是因為伺服器此影片片源不穩定

然後我的程式也不知道執行到哪裡去了 也都沒動了

我得再找找 Bug 點在哪裡

**Comment by hgalytoby** [comment]
> 我只載過化物語第一集，也有卡過，不過重開就會好一下子了。

OK，我可能知道問題點在哪裡了!

我使用的 GUI 套件是 Qt。

不知道為什麼突然在 Thread 有物件斷了信號的樣子，但是並沒有使程式崩潰，而是卡著不動。

當卡著不動的時候去載別集動漫就會出現

```QObject::connect: Cannot queue arguments of type 'QItemSelection' (Make sure 'QItemSelection' is registered using qRegisterMetaType().)```

目前這個問題只能重開程式，我還沒有辦法解決這個問題。
