### ISSUE TITLE
版面會破版

### ISSUE THREAD

**Issue by Chen913** [hgalytoby/MyselfAnimeDownloader#6]
運行系統為win10
如系統設定中:設定>系統>顯示器>變更文字、應用程式與其他項目的大小  使用150%會產生破版，導致某些按鈕被其他物件覆蓋，無法點集
必須改為100%才能正確顯示，但100%顯示上又嫌過小，
希望能支援150%的排版

另外，[物語系列第二季](https://myself-bbs.com/thread-44370-1-1.html)則是無論何種顯示比例均會破版，希望改善

[點此查看破版情形](https://user-images.githubusercontent.com/71249961/110200511-5ff63880-7e99-11eb-8c5d-1bab555cf5ea.png)

**Comment by hgalytoby** [comment]
好!

我知道了!

嘗試修修看!

**Comment by hgalytoby** [comment]
> 運行系統為win10
> 如系統設定中:設定>系統>顯示器>變更文字、應用程式與其他項目的大小 使用150%會產生破版，導致某些按鈕被其他物件覆蓋，無法點集
> 必須改為100%才能正確顯示，但100%顯示上又嫌過小，
> 希望能支援150%的排版
> 
> 另外，[物語系列第二季](https://myself-bbs.com/thread-44370-1-1.html)則是無論何種顯示比例均會破版，希望改善
> 
> [點此查看破版情形](https://user-images.githubusercontent.com/71249961/110200511-5ff63880-7e99-11eb-8c5d-1bab555cf5ea.png)

好!

我知道了!

嘗試修修看!

**Comment by hgalytoby** [comment]
你的問題我解決了，但有人有發現其他問題，所以我會一起解決問題，因我最近有專案要解決，預計要1~2個星期的時間，才會上傳新版本。

**Comment by Chen913** [comment]
> 你的問題我可能已經解決了，等我更新後你再回報給我看還有沒有問題。
> 
> 另外，因有人有發現其他問題噢我最近有專案要解決，所以我打算一起解決問題，預計要1~2個星期的時間，才會上傳新版本。

謝謝作者

**Comment by hgalytoby** [comment]
> > 你的問題我可能已經解決了，等我更新後你再回報給我看還有沒有問題。
> > 另外，因有人有發現其他問題噢我最近有專案要解決，所以我打算一起解決問題，預計要1~2個星期的時間，才會上傳新版本。
> 
> 謝謝作者

更新了。

你試試看這樣的125% 150% 你能不能接受，我是 Google Qt 套件去看別人怎麼解決125% 150%的問題。

如果還有問題，麻煩請再告知我!

謝謝。

**Comment by Chen913** [comment]
> > > 你的問題我可能已經解決了，等我更新後你再回報給我看還有沒有問題。
> > > 另外，因有人有發現其他問題噢我最近有專案要解決，所以我打算一起解決問題，預計要1~2個星期的時間，才會上傳新版本。
> > 
> > 
> > 謝謝作者
> 
> 更新了。
> 
> https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/ver1.1.0
> 
> 你試試看這樣的125% 150% 你能不能接受，我是 Google `Qt` 套件去看別人怎麼解決125% 150%的問題。
> 
> 如果還有問題，麻煩請再告知我!
> 
> 謝謝。

版面不會因為150%而疊在一起，但現在變成整個視窗變成原本的150%而超出螢幕
要稍微拖動視窗才能按到邊緣的物件，
不過已經在能使用的範圍了

不知道這問題能不能用scrollbar的方式解決
超出的的部分可以橫向滾動

**Comment by hgalytoby** [comment]
> 版面不會因為150%而疊在一起，但現在變成整個視窗變成原本的150%而超出螢幕
> 要稍微拖動視窗才能按到邊緣的物件，
> 不過已經在能使用的範圍了
> 
> 不知道這問題能不能用scrollbar的方式解決
> 超出的的部分可以橫向滾動


我不知道有沒有解決這問題的方法，我想應該只能這樣(不肯定)。

因為不只是我的程式會這樣，如果改成 150% 後，其他一些程式的視窗也會變成跟我一樣需要拖動視窗才對。

舉個例子: 我用 `ubuntu` 改成200%後，我的設定視窗也會變得很大，需要拖動視窗 看左 看右 看上 看下。

但是很多其他程式是允許使用者自己更改視窗大小。

因為我當初設計的時候，`UI`版面設計並沒有很會用，所以當時我將程式的視窗寬高鎖死後，接著添加物件。

所以我現在不鎖死 `UI`大小的話，允許使用者更改大小的話版面會破板。

現在除了我修改 `UI`檔後並開啟使用者自由更改視窗大小，不然現在只能這樣變成全螢幕後還要拖動視窗才行。

**Comment by hgalytoby** [comment]
如果還有問題，請再告知我。

如果您喜歡此專案，請幫我在頁面右上角按星星，是我更新最大的動力，謝謝您!
