### ISSUE TITLE
影片下載下來後，並不是完整(完善)的

### ISSUE THREAD

**Issue by Amagami** [hgalytoby/MyselfAnimeDownloader#7]
作者您好，很謝謝您提供這麼方便的程式
我一直以來都很想把myself網站的影片下載下來看
畢竟站內 "P2P" 會有卡頓的問題，可以說是完全解決了我的困擾

但是有一點這邊想請教一下，影片下載下來之後
有時候播放到某個時間，會卡卡的，這邊的卡卡的不是指影片暫停了
而是畫面和聲音都變得緩慢

也有小片段畫面重複2次的情況發生
請問這樣的問題是一直以來都有存在的嗎?
還是其實是我自己本身有甚麼設定或者是防毒軟體干擾導致的呢?

還請您幫小弟解惑，辛苦了，謝謝

**Comment by hgalytoby** [comment]
> 作者您好，很謝謝您提供這麼方便的程式
當初面試沒作品就找隨便個網站做爬蟲下載動漫，有幫助到您就好。

> 我一直以來都很想把myself網站的影片下載下來看
> 畢竟站內 "P2P" 會有卡頓的問題，可以說是完全解決了我的困擾

> 但是有一點這邊想請教一下，影片下載下來之後
> 有時候播放到某個時間，會卡卡的，這邊的卡卡的不是指影片暫停了
> 而是畫面和聲音都變得緩慢
畢竟我沒有下載 Myself 的動畫來看所以我也不清楚。
想知道 你有在下載途中關閉程式重新打開下載嗎?


> 也有小片段畫面重複2次的情況發生
> 請問這樣的問題是一直以來都有存在的嗎?
> 還是其實是我自己本身有甚麼設定或者是防毒軟體干擾導致的呢?

這個是我的問題，如果是下載的時候關閉程式下次打開，有機會會這樣，我的續傳並沒有寫得很好，難免會發生這種事情，甚至常常發生。
之後我在修修看。

> 還請您幫小弟解惑，辛苦了，謝謝
不客氣。

**Comment by Amagami** [comment]
那再請問一下作者，假設今天我是開機後直接打開程式
然後下載指定我想觀賞的動漫作品
就不會發生這樣的問題了嗎?

謝謝。

**Comment by hgalytoby** [comment]
> 那再請問一下作者，假設今天我是開機後直接打開程式
> 然後下載指定我想觀賞的動漫作品
> 就不會發生這樣的問題了嗎?
> 
> 謝謝。

照理來講，程式打開後不要關閉直接載到底，應該不會出任何問題。

如果還有此問題，你告訴我是哪個動漫，我去下載來看。

**Comment by Amagami** [comment]
作者您好，昨天看到您的留言後
我就在傍晚開始測試了
我先將電腦直接重新開機後，打開程式直接下 "四月是你的謊言" 這部動漫
中間完全沒有關閉程式，是直接讓它從頭下載到尾的

應片安裝位置我選擇再D槽，下載速度選擇 "星爆"，下載數量設定為10
剛剛觀看到第7集的時候發生了片段重複2次的情況
不過這次的情形比上一次好了，之前差不多第2集就會有這樣的狀況發生
這一次一直到第7集才有，不知道是甚麼原因

動漫名稱:四月是你的謊言
以上，謝謝作者

**Comment by hgalytoby** [comment]
> 作者您好，昨天看到您的留言後
> 我就在傍晚開始測試了
> 我先將電腦直接重新開機後，打開程式直接下 "四月是你的謊言" 這部動漫
> 中間完全沒有關閉程式，是直接讓它從頭下載到尾的
> 
> 應片安裝位置我選擇再D槽，下載速度選擇 "星爆"，下載數量設定為10
> 剛剛觀看到第7集的時候發生了片段重複2次的情況
> 不過這次的情形比上一次好了，之前差不多第2集就會有這樣的狀況發生
> 這一次一直到第7集才有，不知道是甚麼原因
> 
> 動漫名稱:四月是你的謊言
> 以上，謝謝作者

重新下載重複片段的動畫級數，還會發生此問題嗎?

**Comment by Amagami** [comment]
這邊與您回報一下
我已經看到第11集了，目前只有第7集有出現狀況
剛剛已照您所說的，將第7集的重新下載

意外的是，原本有問題的部分，重新下載後居然消失了
以上，謝謝作者

**Comment by hgalytoby** [comment]
> 這邊與您回報一下
> 我已經看到第11集了，目前只有第7集有出現狀況
> 剛剛已照您所說的，將第7集的重新下載
> 
> 意外的是，原本有問題的部分，重新下載後居然消失了
> 以上，謝謝作者

目前我找不到不關閉程式下載動漫還會發生重複片段發生的問題，我找不到問題點。

但下次更新我會大改下載動漫那部分的程式碼，至少避免不關閉程式時下載動漫會發生重複片段的問題，但續傳還是不保證不會發生問題，得再嘗試才行。

我還有一個問題，你會想要邊下載邊看嗎?

**Comment by Amagami** [comment]
作者您好，以下單純只是小弟的想法，您參考即可
我在想，會不會 "重複下載片段" 這件事情本身，有其他是因為內建的程式在干擾?
ex : 防毒軟體...等等
或許作者可以朝著這個方向去找bug?

「我還有一個問題，你會想要邊下載邊看嗎?」
關於作者您的這個問題，我個人應該是不會想要這麼做
這可能和個性有關吧，我喜歡完整的東西都下載下來後一次性地觀賞

至於其他有使用您的作品的網友怎麼想，就不清楚了
不過我想那會是一個好功能的!!!

小弟的程式觀念，應該還停留在比初學者稍微好一點的階段
大致上想一下「邊下載邊看」這個功能，程式的完善程度，要求應該會更高

以上，謝謝作者^^

**Comment by hgalytoby** [comment]
> 作者您好，以下單純只是小弟的想法，您參考即可
> 我在想，會不會 "重複下載片段" 這件事情本身，有其他是因為內建的程式在干擾?
> ex : 防毒軟體...等等
> 或許作者可以朝著這個方向去找bug?
> 
> 「我還有一個問題，你會想要邊下載邊看嗎?」
> 關於作者您的這個問題，我個人應該是不會想要這麼做
> 這可能和個性有關吧，我喜歡完整的東西都下載下來後一次性地觀賞
> 
> 至於其他有使用您的作品的網友怎麼想，就不清楚了
> 不過我想那會是一個好功能的!!!
> 
> 小弟的程式觀念，應該還停留在比初學者稍微好一點的階段
> 大致上想一下「邊下載邊看」這個功能，程式的完善程度，要求應該會更高
> 
> 以上，謝謝作者^^

不會有防毒的問題導致重複下載片段。

主要是邊載邊看才會發生重複的片段。

因為續傳方法的關係，必須記錄上一次下載到哪裡，然而如果正在寫入影片的時候，程式被關閉就會有寫入檔案後沒有記錄下來，導致下次打開又會再去寫入一次已寫入的影片，就會發生重複片段的事情。

**Comment by Amagami** [comment]
我知道了，那就等待之後作者更新內容

以上，謝謝

**Comment by hgalytoby** [comment]
> 我知道了，那就等待之後作者更新內容
> 
> 以上，謝謝

更新了。

如果還有問題，麻煩請告知我。

謝謝。

**Comment by hgalytoby** [comment]
如果還有問題，請再告知我。

如果您喜歡此專案，請幫我在頁面右上角按星星，是我更新最大的動力，謝謝您!
