### ISSUE TITLE
下載有時候會卡死

### ISSUE THREAD

**Issue by morris13579** [hgalytoby/MyselfAnimeDownloader#8]
當下載的檔案時，可能會因為下載的某一個線程一直未完成，導致下載卡在某個進度，根據我的想法，
我認為是在DownloadVideo中的video的download_request(url=url, stream=False, timeout=3)就是myself_thread.py的282行
，因為某些原因導致卡死，影響後續的下載，我認為解決方法可以加入一些超時的，當超時重啟線程。

**Comment by hgalytoby** [comment]
> 當下載的檔案時，可能會因為下載的某一個線程一直未完成，導致下載卡在某個進度，根據我的想法，
> 我認為是在DownloadVideo中的video的download_request（URL = URL，stream = False， timeout = 3）就是myself_thread.py的282行
> ，因為某些原因導致卡死，影響後續的下載，我認為解決方法可以加入一些超時的，當超時重啟線程。

某些原因導致卡死，影響後續的下載是指 某一級卡死導致其他級數下載也卡死了嗎？

確實我有發現卡死的問題，我測的數量很少都是發現在下載比較久遠的動畫時才出現的問題。

我的`download_request(url=url, stream=False,  timeout=3)` 已經有超時的設定了。

我猜想可能是要失敗達到`一定的次數`，直接砍掉 thread 重新執行新的 thread ，或許可以解決此問題，下次更新我改成這樣試試看。

**Comment by morris13579** [comment]
原本想說可以類似singal的SIGALRM(但是只能在unix使用)讓download_request可以超時發出錯誤，因為我發現requests.get的timeout有時候會沒有用。

**Comment by hgalytoby** [comment]
> 原本想說可以類似singal的SIGALRM(但是只能在unix使用)讓download_request可以超時發出錯誤，因為我發現requests.get的timeout有時候會沒有用。

所以  `某些原因導致卡死，影響後續的下載是指 某一級卡死導致其他級數下載也卡死了嗎`？

**Comment by morris13579** [comment]
對就是發生類似這種情況，因為我看程式的寫法是，假設有n個m8u3個檔案他會一個一個等待前面的存檔後才會繼續，隨以當其中一個卡住就會導致後面的無限卡死。推測真的是已經與伺服器連接但是下載不知原因超級久或是直接沒在下載。

**Comment by hgalytoby** [comment]
> 對就是發生類似這種情況，因為我看程式的寫法是，假設有n個m8u3個檔案他會一個一個等待前面的存檔後才會繼續，隨以當其中一個卡住就會導致後面的無限卡死。推測真的是已經與伺服器連接但是下載不知原因超級久或是直接沒在下載。

我下載 `m3u8` 前有個  `self.turn_me()`

應該不會有一個卡住後面的全部卡住才對。

假如原因是跟伺服器成功握手，但是處理事情卡住導致永遠進度不會動了，那或許得在開一個 thread 過了一定的秒數檢查 .ts。

如果 .ts 沒有在變動，就砍掉 thread 重新來一次。

還有 requests error 失敗的次數達到一定的數字也砍掉重新來一次。

**Comment by hgalytoby** [comment]
> 對就是發生類似這種情況，因為我看程式的寫法是，假設有n個m8u3個檔案他會一個一個等待前面的存檔後才會繼續，隨以當其中一個卡住就會導致後面的無限卡死。推測真的是已經與伺服器連接但是下載不知原因超級久或是直接沒在下載。

我更新了!

如果你還有再用的話，還有發生卡死的問題，請再告知我。

謝謝您。
