### ISSUE TITLE
Fatal error detected: Failed to execute script main

### ISSUE THREAD

**Issue by Senzagu** [hgalytoby/MyselfAnimeDownloader#9]
我今天早上還能用，但剛剛再開就出現這問題了。
P.S. 我不太懂電腦

**Comment by hgalytoby** [comment]
> 我今天早上還能用，但剛剛再開就出現這問題了。
> P.S. 我不太懂電腦

告訴我你是什麼系統.

是執行執行檔還是執行 code.

如果可以你能附圖給我看嗎?

附圖很簡單，對圖按ctrl+c ，接著到輸入訊息的視窗按下 ctrl+v 就能附圖了。

**Comment by Senzagu** [comment]
我用的是Win10

是執行檔的

我的意思是不懂那些程式碼，電腦的還是能掌握，看到上來的大大都說一堆編碼，所以才備註一下。
![error](https://user-images.githubusercontent.com/82928272/115551495-be5a6780-a2dd-11eb-8beb-d02357464669.jpg)

**Comment by hgalytoby** [comment]
> 我用的是Win10
> 
> 是執行檔的
> 
> 我的意思是不懂那些程式碼，電腦的還是能掌握，看到上來的大大都說一堆編碼，所以才備註一下。
> ![error](https://user-images.githubusercontent.com/82928272/115551495-be5a6780-a2dd-11eb-8beb-d02357464669.jpg)

你下載的是最新版本嗎?

你把除了 MyselfAnime + 你下載的動漫資料夾以外的資料夾全部砍掉再重新執行試試看。

如果還不行就重新下載試試看。

https://github.com/hgalytoby/MyselfAnimeDownloader/releases/tag/ver1.1.0

**Comment by Senzagu** [comment]
我把`MyselfAnime` + `我下載的動漫資料夾`以外都刪掉重新執行，然後就成功了！
感謝！
